// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// CreateEnvironment
    /// </summary>
    public partial class CreateEnvironment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateEnvironment" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="project">project</param>
        [JsonConstructor]
        public CreateEnvironment(string name, string project)
        {
            Name = name;
            Project = project;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Project
        /// </summary>
        [JsonPropertyName("project")]
        public string Project { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateEnvironment {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            if (this.Name != null) {
                // Name (string) pattern
                Regex regexName = new Regex(@"^(?!(\.|\.\.|open|yaml))[a-zA-Z0-9-_.]+$", RegexOptions.CultureInvariant);

                if (!regexName.Match(this.Name).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
                }
            }

            // Project (string) maxLength
            if (this.Project != null && this.Project.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Project, length must be less than 100.", new [] { "Project" });
            }

            // Project (string) minLength
            if (this.Project != null && this.Project.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Project, length must be greater than 1.", new [] { "Project" });
            }

            if (this.Project != null) {
                // Project (string) pattern
                Regex regexProject = new Regex(@"^(?!(\.|\.\.|default))[a-zA-Z0-9-_.]+$", RegexOptions.CultureInvariant);

                if (!regexProject.Match(this.Project).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Project, must match a pattern of " + regexProject, new [] { "Project" });
                }
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateEnvironment" />
    /// </summary>
    public class CreateEnvironmentJsonConverter : JsonConverter<CreateEnvironment>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateEnvironment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateEnvironment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> project = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "project":
                            project = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateEnvironment.", nameof(name));

            if (!project.IsSet)
                throw new ArgumentException("Property is required for class CreateEnvironment.", nameof(project));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateEnvironment.");

            if (project.IsSet && project.Value == null)
                throw new ArgumentNullException(nameof(project), "Property is not nullable for class CreateEnvironment.");

            return new CreateEnvironment(name.Value!, project.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateEnvironment createEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, createEnvironment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, CreateEnvironment createEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createEnvironment.Name == null)
                throw new ArgumentNullException(nameof(createEnvironment.Name), "Property is required for class CreateEnvironment.");

            if (createEnvironment.Project == null)
                throw new ArgumentNullException(nameof(createEnvironment.Project), "Property is required for class CreateEnvironment.");

            writer.WriteString("name", createEnvironment.Name);

            writer.WriteString("project", createEnvironment.Project);
        }
    }
}
