// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentTag
    /// </summary>
    public partial class EnvironmentTag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentTag" /> class.
        /// </summary>
        /// <param name="created">created</param>
        /// <param name="editorLogin">editorLogin</param>
        /// <param name="editorName">editorName</param>
        /// <param name="modified">modified</param>
        /// <param name="name">name</param>
        /// <param name="value">value</param>
        [JsonConstructor]
        public EnvironmentTag(string created, string editorLogin, string editorName, string modified, string name, Option<string?> value = default)
        {
            Created = created;
            EditorLogin = editorLogin;
            EditorName = editorName;
            Modified = modified;
            Name = name;
            ValueOption = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public string Created { get; set; }

        /// <summary>
        /// Gets or Sets EditorLogin
        /// </summary>
        [JsonPropertyName("editorLogin")]
        public string EditorLogin { get; set; }

        /// <summary>
        /// Gets or Sets EditorName
        /// </summary>
        [JsonPropertyName("editorName")]
        public string EditorName { get; set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [JsonPropertyName("modified")]
        public string Modified { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string? Value { get { return this.ValueOption; } set { this.ValueOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentTag {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  EditorLogin: ").Append(EditorLogin).Append("\n");
            sb.Append("  EditorName: ").Append(EditorName).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentTag" />
    /// </summary>
    public class EnvironmentTagJsonConverter : JsonConverter<EnvironmentTag>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentTag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentTag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> created = default;
            Option<string?> editorLogin = default;
            Option<string?> editorName = default;
            Option<string?> modified = default;
            Option<string?> name = default;
            Option<string?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "created":
                            created = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "editorLogin":
                            editorLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "editorName":
                            editorName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "modified":
                            modified = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentTag.", nameof(created));

            if (!editorLogin.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentTag.", nameof(editorLogin));

            if (!editorName.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentTag.", nameof(editorName));

            if (!modified.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentTag.", nameof(modified));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentTag.", nameof(name));

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class EnvironmentTag.");

            if (editorLogin.IsSet && editorLogin.Value == null)
                throw new ArgumentNullException(nameof(editorLogin), "Property is not nullable for class EnvironmentTag.");

            if (editorName.IsSet && editorName.Value == null)
                throw new ArgumentNullException(nameof(editorName), "Property is not nullable for class EnvironmentTag.");

            if (modified.IsSet && modified.Value == null)
                throw new ArgumentNullException(nameof(modified), "Property is not nullable for class EnvironmentTag.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class EnvironmentTag.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class EnvironmentTag.");

            return new EnvironmentTag(created.Value!, editorLogin.Value!, editorName.Value!, modified.Value!, name.Value!, value);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentTag environmentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentTag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentTag environmentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentTag.Created == null)
                throw new ArgumentNullException(nameof(environmentTag.Created), "Property is required for class EnvironmentTag.");

            if (environmentTag.EditorLogin == null)
                throw new ArgumentNullException(nameof(environmentTag.EditorLogin), "Property is required for class EnvironmentTag.");

            if (environmentTag.EditorName == null)
                throw new ArgumentNullException(nameof(environmentTag.EditorName), "Property is required for class EnvironmentTag.");

            if (environmentTag.Modified == null)
                throw new ArgumentNullException(nameof(environmentTag.Modified), "Property is required for class EnvironmentTag.");

            if (environmentTag.Name == null)
                throw new ArgumentNullException(nameof(environmentTag.Name), "Property is required for class EnvironmentTag.");

            if (environmentTag.ValueOption.IsSet && environmentTag.Value == null)
                throw new ArgumentNullException(nameof(environmentTag.Value), "Property is required for class EnvironmentTag.");

            writer.WriteString("created", environmentTag.Created);

            writer.WriteString("editorLogin", environmentTag.EditorLogin);

            writer.WriteString("editorName", environmentTag.EditorName);

            writer.WriteString("modified", environmentTag.Modified);

            writer.WriteString("name", environmentTag.Name);

            if (environmentTag.ValueOption.IsSet)
                writer.WriteString("value", environmentTag.Value);
        }
    }
}
