// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentDiagnostics
    /// </summary>
    public partial class EnvironmentDiagnostics : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentDiagnostics" /> class.
        /// </summary>
        /// <param name="diagnostics">diagnostics</param>
        [JsonConstructor]
        public EnvironmentDiagnostics(Option<List<EnvironmentDiagnostic>?> diagnostics = default)
        {
            DiagnosticsOption = diagnostics;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Diagnostics
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EnvironmentDiagnostic>?> DiagnosticsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Diagnostics
        /// </summary>
        [JsonPropertyName("diagnostics")]
        public List<EnvironmentDiagnostic>? Diagnostics { get { return this.DiagnosticsOption; } set { this.DiagnosticsOption = new Option<List<EnvironmentDiagnostic>?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentDiagnostics {\n");
            sb.Append("  Diagnostics: ").Append(Diagnostics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentDiagnostics" />
    /// </summary>
    public class EnvironmentDiagnosticsJsonConverter : JsonConverter<EnvironmentDiagnostics>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentDiagnostics" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentDiagnostics Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<EnvironmentDiagnostic>?> diagnostics = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "diagnostics":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                diagnostics = new Option<List<EnvironmentDiagnostic>?>(JsonSerializer.Deserialize<List<EnvironmentDiagnostic>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (diagnostics.IsSet && diagnostics.Value == null)
                throw new ArgumentNullException(nameof(diagnostics), "Property is not nullable for class EnvironmentDiagnostics.");

            return new EnvironmentDiagnostics(diagnostics);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentDiagnostics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDiagnostics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentDiagnostics environmentDiagnostics, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentDiagnostics, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentDiagnostics" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDiagnostics"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentDiagnostics environmentDiagnostics, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentDiagnostics.DiagnosticsOption.IsSet && environmentDiagnostics.Diagnostics == null)
                throw new ArgumentNullException(nameof(environmentDiagnostics.Diagnostics), "Property is required for class EnvironmentDiagnostics.");

            if (environmentDiagnostics.DiagnosticsOption.IsSet)
            {
                writer.WritePropertyName("diagnostics");
                JsonSerializer.Serialize(writer, environmentDiagnostics.Diagnostics, jsonSerializerOptions);
            }
        }
    }
}
