// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentDiagnostic
    /// </summary>
    public partial class EnvironmentDiagnostic : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentDiagnostic" /> class.
        /// </summary>
        /// <param name="summary">summary</param>
        /// <param name="path">path</param>
        /// <param name="range">range</param>
        [JsonConstructor]
        public EnvironmentDiagnostic(string summary, Option<string?> path = default, Option<Range?> range = default)
        {
            Summary = summary;
            PathOption = path;
            RangeOption = range;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [JsonPropertyName("summary")]
        public string Summary { get; set; }

        /// <summary>
        /// Used to track the state of Path
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PathOption { get; private set; }

        /// <summary>
        /// Gets or Sets Path
        /// </summary>
        [JsonPropertyName("path")]
        public string? Path { get { return this.PathOption; } set { this.PathOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Range
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Range?> RangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public Range? Range { get { return this.RangeOption; } set { this.RangeOption = new Option<Range?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentDiagnostic {\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentDiagnostic" />
    /// </summary>
    public class EnvironmentDiagnosticJsonConverter : JsonConverter<EnvironmentDiagnostic>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentDiagnostic" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentDiagnostic Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> summary = default;
            Option<string?> path = default;
            Option<Range?> range = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "summary":
                            summary = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "range":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                range = new Option<Range?>(JsonSerializer.Deserialize<Range>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!summary.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentDiagnostic.", nameof(summary));

            if (summary.IsSet && summary.Value == null)
                throw new ArgumentNullException(nameof(summary), "Property is not nullable for class EnvironmentDiagnostic.");

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class EnvironmentDiagnostic.");

            if (range.IsSet && range.Value == null)
                throw new ArgumentNullException(nameof(range), "Property is not nullable for class EnvironmentDiagnostic.");

            return new EnvironmentDiagnostic(summary.Value!, path, range);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentDiagnostic" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDiagnostic"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentDiagnostic environmentDiagnostic, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentDiagnostic, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentDiagnostic" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDiagnostic"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentDiagnostic environmentDiagnostic, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentDiagnostic.Summary == null)
                throw new ArgumentNullException(nameof(environmentDiagnostic.Summary), "Property is required for class EnvironmentDiagnostic.");

            if (environmentDiagnostic.PathOption.IsSet && environmentDiagnostic.Path == null)
                throw new ArgumentNullException(nameof(environmentDiagnostic.Path), "Property is required for class EnvironmentDiagnostic.");

            if (environmentDiagnostic.RangeOption.IsSet && environmentDiagnostic.Range == null)
                throw new ArgumentNullException(nameof(environmentDiagnostic.Range), "Property is required for class EnvironmentDiagnostic.");

            writer.WriteString("summary", environmentDiagnostic.Summary);

            if (environmentDiagnostic.PathOption.IsSet)
                writer.WriteString("path", environmentDiagnostic.Path);

            if (environmentDiagnostic.RangeOption.IsSet)
            {
                writer.WritePropertyName("range");
                JsonSerializer.Serialize(writer, environmentDiagnostic.Range, jsonSerializerOptions);
            }
        }
    }
}
