// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentRevisionTags
    /// </summary>
    public partial class EnvironmentRevisionTags : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentRevisionTags" /> class.
        /// </summary>
        /// <param name="nextToken">nextToken</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public EnvironmentRevisionTags(Option<string?> nextToken = default, Option<List<EnvironmentRevisionTag>?> tags = default)
        {
            NextTokenOption = nextToken;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of NextToken
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NextTokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextToken
        /// </summary>
        [JsonPropertyName("nextToken")]
        public string? NextToken { get { return this.NextTokenOption; } set { this.NextTokenOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EnvironmentRevisionTag>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<EnvironmentRevisionTag>? Tags { get { return this.TagsOption; } set { this.TagsOption = new Option<List<EnvironmentRevisionTag>?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentRevisionTags {\n");
            sb.Append("  NextToken: ").Append(NextToken).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentRevisionTags" />
    /// </summary>
    public class EnvironmentRevisionTagsJsonConverter : JsonConverter<EnvironmentRevisionTags>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentRevisionTags" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentRevisionTags Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nextToken = default;
            Option<List<EnvironmentRevisionTag>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nextToken":
                            nextToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tags":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tags = new Option<List<EnvironmentRevisionTag>?>(JsonSerializer.Deserialize<List<EnvironmentRevisionTag>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (nextToken.IsSet && nextToken.Value == null)
                throw new ArgumentNullException(nameof(nextToken), "Property is not nullable for class EnvironmentRevisionTags.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class EnvironmentRevisionTags.");

            return new EnvironmentRevisionTags(nextToken, tags);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentRevisionTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentRevisionTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentRevisionTags environmentRevisionTags, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentRevisionTags, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentRevisionTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentRevisionTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentRevisionTags environmentRevisionTags, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentRevisionTags.NextTokenOption.IsSet && environmentRevisionTags.NextToken == null)
                throw new ArgumentNullException(nameof(environmentRevisionTags.NextToken), "Property is required for class EnvironmentRevisionTags.");

            if (environmentRevisionTags.TagsOption.IsSet && environmentRevisionTags.Tags == null)
                throw new ArgumentNullException(nameof(environmentRevisionTags.Tags), "Property is required for class EnvironmentRevisionTags.");

            if (environmentRevisionTags.NextTokenOption.IsSet)
                writer.WriteString("nextToken", environmentRevisionTags.NextToken);

            if (environmentRevisionTags.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, environmentRevisionTags.Tags, jsonSerializerOptions);
            }
        }
    }
}
