// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentDefinition
    /// </summary>
    public partial class EnvironmentDefinition : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentDefinition" /> class.
        /// </summary>
        /// <param name="imports">imports</param>
        /// <param name="values">values</param>
        [JsonConstructor]
        public EnvironmentDefinition(Option<List<string>?> imports = default, Option<EnvironmentDefinitionValues?> values = default)
        {
            ImportsOption = imports;
            ValuesOption = values;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Imports
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> ImportsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Imports
        /// </summary>
        [JsonPropertyName("imports")]
        public List<string>? Imports { get { return this.ImportsOption; } set { this.ImportsOption = new Option<List<string>?>(value); } }

        /// <summary>
        /// Used to track the state of Values
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EnvironmentDefinitionValues?> ValuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Values
        /// </summary>
        [JsonPropertyName("values")]
        public EnvironmentDefinitionValues? Values { get { return this.ValuesOption; } set { this.ValuesOption = new Option<EnvironmentDefinitionValues?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentDefinition {\n");
            sb.Append("  Imports: ").Append(Imports).Append("\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentDefinition" />
    /// </summary>
    public class EnvironmentDefinitionJsonConverter : JsonConverter<EnvironmentDefinition>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentDefinition" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentDefinition Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> imports = default;
            Option<EnvironmentDefinitionValues?> values = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "imports":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                imports = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "values":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                values = new Option<EnvironmentDefinitionValues?>(JsonSerializer.Deserialize<EnvironmentDefinitionValues>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (imports.IsSet && imports.Value == null)
                throw new ArgumentNullException(nameof(imports), "Property is not nullable for class EnvironmentDefinition.");

            if (values.IsSet && values.Value == null)
                throw new ArgumentNullException(nameof(values), "Property is not nullable for class EnvironmentDefinition.");

            return new EnvironmentDefinition(imports, values);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentDefinition environmentDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentDefinition, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentDefinition" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentDefinition"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentDefinition environmentDefinition, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentDefinition.ImportsOption.IsSet && environmentDefinition.Imports == null)
                throw new ArgumentNullException(nameof(environmentDefinition.Imports), "Property is required for class EnvironmentDefinition.");

            if (environmentDefinition.ValuesOption.IsSet && environmentDefinition.Values == null)
                throw new ArgumentNullException(nameof(environmentDefinition.Values), "Property is required for class EnvironmentDefinition.");

            if (environmentDefinition.ImportsOption.IsSet)
            {
                writer.WritePropertyName("imports");
                JsonSerializer.Serialize(writer, environmentDefinition.Imports, jsonSerializerOptions);
            }
            if (environmentDefinition.ValuesOption.IsSet)
            {
                writer.WritePropertyName("values");
                JsonSerializer.Serialize(writer, environmentDefinition.Values, jsonSerializerOptions);
            }
        }
    }
}
