// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EnvironmentRevisionTag
    /// </summary>
    public partial class EnvironmentRevisionTag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnvironmentRevisionTag" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="revision">revision</param>
        /// <param name="created">created</param>
        /// <param name="editorLogin">editorLogin</param>
        /// <param name="editorName">editorName</param>
        /// <param name="modified">modified</param>
        [JsonConstructor]
        public EnvironmentRevisionTag(string name, int revision, Option<string?> created = default, Option<string?> editorLogin = default, Option<string?> editorName = default, Option<string?> modified = default)
        {
            Name = name;
            Revision = revision;
            CreatedOption = created;
            EditorLoginOption = editorLogin;
            EditorNameOption = editorName;
            ModifiedOption = modified;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Revision
        /// </summary>
        [JsonPropertyName("revision")]
        public int Revision { get; set; }

        /// <summary>
        /// Used to track the state of Created
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CreatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public string? Created { get { return this.CreatedOption; } set { this.CreatedOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of EditorLogin
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EditorLoginOption { get; private set; }

        /// <summary>
        /// Gets or Sets EditorLogin
        /// </summary>
        [JsonPropertyName("editorLogin")]
        public string? EditorLogin { get { return this.EditorLoginOption; } set { this.EditorLoginOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of EditorName
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EditorNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets EditorName
        /// </summary>
        [JsonPropertyName("editorName")]
        public string? EditorName { get { return this.EditorNameOption; } set { this.EditorNameOption = new Option<string?>(value); } }

        /// <summary>
        /// Used to track the state of Modified
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ModifiedOption { get; private set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [JsonPropertyName("modified")]
        public string? Modified { get { return this.ModifiedOption; } set { this.ModifiedOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnvironmentRevisionTag {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  EditorLogin: ").Append(EditorLogin).Append("\n");
            sb.Append("  EditorName: ").Append(EditorName).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EnvironmentRevisionTag" />
    /// </summary>
    public class EnvironmentRevisionTagJsonConverter : JsonConverter<EnvironmentRevisionTag>
    {
        /// <summary>
        /// Deserializes json to <see cref="EnvironmentRevisionTag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EnvironmentRevisionTag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<int?> revision = default;
            Option<string?> created = default;
            Option<string?> editorLogin = default;
            Option<string?> editorName = default;
            Option<string?> modified = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "revision":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                revision = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "created":
                            created = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "editorLogin":
                            editorLogin = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "editorName":
                            editorName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "modified":
                            modified = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentRevisionTag.", nameof(name));

            if (!revision.IsSet)
                throw new ArgumentException("Property is required for class EnvironmentRevisionTag.", nameof(revision));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class EnvironmentRevisionTag.");

            if (revision.IsSet && revision.Value == null)
                throw new ArgumentNullException(nameof(revision), "Property is not nullable for class EnvironmentRevisionTag.");

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class EnvironmentRevisionTag.");

            if (editorLogin.IsSet && editorLogin.Value == null)
                throw new ArgumentNullException(nameof(editorLogin), "Property is not nullable for class EnvironmentRevisionTag.");

            if (editorName.IsSet && editorName.Value == null)
                throw new ArgumentNullException(nameof(editorName), "Property is not nullable for class EnvironmentRevisionTag.");

            if (modified.IsSet && modified.Value == null)
                throw new ArgumentNullException(nameof(modified), "Property is not nullable for class EnvironmentRevisionTag.");

            return new EnvironmentRevisionTag(name.Value!, revision.Value!.Value!, created, editorLogin, editorName, modified);
        }

        /// <summary>
        /// Serializes a <see cref="EnvironmentRevisionTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentRevisionTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EnvironmentRevisionTag environmentRevisionTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, environmentRevisionTag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EnvironmentRevisionTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="environmentRevisionTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EnvironmentRevisionTag environmentRevisionTag, JsonSerializerOptions jsonSerializerOptions)
        {
            if (environmentRevisionTag.Name == null)
                throw new ArgumentNullException(nameof(environmentRevisionTag.Name), "Property is required for class EnvironmentRevisionTag.");

            if (environmentRevisionTag.CreatedOption.IsSet && environmentRevisionTag.Created == null)
                throw new ArgumentNullException(nameof(environmentRevisionTag.Created), "Property is required for class EnvironmentRevisionTag.");

            if (environmentRevisionTag.EditorLoginOption.IsSet && environmentRevisionTag.EditorLogin == null)
                throw new ArgumentNullException(nameof(environmentRevisionTag.EditorLogin), "Property is required for class EnvironmentRevisionTag.");

            if (environmentRevisionTag.EditorNameOption.IsSet && environmentRevisionTag.EditorName == null)
                throw new ArgumentNullException(nameof(environmentRevisionTag.EditorName), "Property is required for class EnvironmentRevisionTag.");

            if (environmentRevisionTag.ModifiedOption.IsSet && environmentRevisionTag.Modified == null)
                throw new ArgumentNullException(nameof(environmentRevisionTag.Modified), "Property is required for class EnvironmentRevisionTag.");

            writer.WriteString("name", environmentRevisionTag.Name);

            writer.WriteNumber("revision", environmentRevisionTag.Revision);

            if (environmentRevisionTag.CreatedOption.IsSet)
                writer.WriteString("created", environmentRevisionTag.Created);

            if (environmentRevisionTag.EditorLoginOption.IsSet)
                writer.WriteString("editorLogin", environmentRevisionTag.EditorLogin);

            if (environmentRevisionTag.EditorNameOption.IsSet)
                writer.WriteString("editorName", environmentRevisionTag.EditorName);

            if (environmentRevisionTag.ModifiedOption.IsSet)
                writer.WriteString("modified", environmentRevisionTag.Modified);
        }
    }
}
