// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// EvaluatedExecutionContext
    /// </summary>
    public partial class EvaluatedExecutionContext : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluatedExecutionContext" /> class.
        /// </summary>
        /// <param name="properties">properties</param>
        /// <param name="schema">schema</param>
        [JsonConstructor]
        public EvaluatedExecutionContext(Option<Dictionary<string, Value>?> properties = default, Option<Object?> schema = default)
        {
            PropertiesOption = properties;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Properties
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Value>?> PropertiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [JsonPropertyName("properties")]
        public Dictionary<string, Value>? Properties { get { return this.PropertiesOption; } set { this.PropertiesOption = new Option<Dictionary<string, Value>?>(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> SchemaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [JsonPropertyName("schema")]
        public Object? Schema { get { return this.SchemaOption; } set { this.SchemaOption = new Option<Object?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EvaluatedExecutionContext {\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EvaluatedExecutionContext" />
    /// </summary>
    public class EvaluatedExecutionContextJsonConverter : JsonConverter<EvaluatedExecutionContext>
    {
        /// <summary>
        /// Deserializes json to <see cref="EvaluatedExecutionContext" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EvaluatedExecutionContext Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, Value>?> properties = default;
            Option<Object?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "properties":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                properties = new Option<Dictionary<string, Value>?>(JsonSerializer.Deserialize<Dictionary<string, Value>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "schema":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                schema = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (properties.IsSet && properties.Value == null)
                throw new ArgumentNullException(nameof(properties), "Property is not nullable for class EvaluatedExecutionContext.");

            return new EvaluatedExecutionContext(properties, schema);
        }

        /// <summary>
        /// Serializes a <see cref="EvaluatedExecutionContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="evaluatedExecutionContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EvaluatedExecutionContext evaluatedExecutionContext, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, evaluatedExecutionContext, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="EvaluatedExecutionContext" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="evaluatedExecutionContext"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, EvaluatedExecutionContext evaluatedExecutionContext, JsonSerializerOptions jsonSerializerOptions)
        {
            if (evaluatedExecutionContext.PropertiesOption.IsSet && evaluatedExecutionContext.Properties == null)
                throw new ArgumentNullException(nameof(evaluatedExecutionContext.Properties), "Property is required for class EvaluatedExecutionContext.");

            if (evaluatedExecutionContext.PropertiesOption.IsSet)
            {
                writer.WritePropertyName("properties");
                JsonSerializer.Serialize(writer, evaluatedExecutionContext.Properties, jsonSerializerOptions);
            }
            if (evaluatedExecutionContext.SchemaOption.IsSet)
                if (evaluatedExecutionContext.SchemaOption.Value != null)
                {
                    writer.WritePropertyName("schema");
                    JsonSerializer.Serialize(writer, evaluatedExecutionContext.Schema, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("schema");
        }
    }
}
