// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// ExprBuiltin
    /// </summary>
    public partial class ExprBuiltin : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExprBuiltin" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="arg">arg</param>
        /// <param name="argSchema">argSchema</param>
        /// <param name="nameRange">nameRange</param>
        [JsonConstructor]
        public ExprBuiltin(string name, Option<Expr?> arg = default, Option<Object?> argSchema = default, Option<Range?> nameRange = default)
        {
            Name = name;
            ArgOption = arg;
            ArgSchemaOption = argSchema;
            NameRangeOption = nameRange;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Arg
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Expr?> ArgOption { get; private set; }

        /// <summary>
        /// Gets or Sets Arg
        /// </summary>
        [JsonPropertyName("arg")]
        public Expr? Arg { get { return this.ArgOption; } set { this.ArgOption = new Option<Expr?>(value); } }

        /// <summary>
        /// Used to track the state of ArgSchema
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> ArgSchemaOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArgSchema
        /// </summary>
        [JsonPropertyName("argSchema")]
        public Object? ArgSchema { get { return this.ArgSchemaOption; } set { this.ArgSchemaOption = new Option<Object?>(value); } }

        /// <summary>
        /// Used to track the state of NameRange
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Range?> NameRangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets NameRange
        /// </summary>
        [JsonPropertyName("nameRange")]
        public Range? NameRange { get { return this.NameRangeOption; } set { this.NameRangeOption = new Option<Range?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExprBuiltin {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Arg: ").Append(Arg).Append("\n");
            sb.Append("  ArgSchema: ").Append(ArgSchema).Append("\n");
            sb.Append("  NameRange: ").Append(NameRange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExprBuiltin" />
    /// </summary>
    public class ExprBuiltinJsonConverter : JsonConverter<ExprBuiltin>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExprBuiltin" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExprBuiltin Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<Expr?> arg = default;
            Option<Object?> argSchema = default;
            Option<Range?> nameRange = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "arg":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                arg = new Option<Expr?>(JsonSerializer.Deserialize<Expr>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "argSchema":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                argSchema = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "nameRange":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                nameRange = new Option<Range?>(JsonSerializer.Deserialize<Range>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ExprBuiltin.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ExprBuiltin.");

            if (arg.IsSet && arg.Value == null)
                throw new ArgumentNullException(nameof(arg), "Property is not nullable for class ExprBuiltin.");

            if (nameRange.IsSet && nameRange.Value == null)
                throw new ArgumentNullException(nameof(nameRange), "Property is not nullable for class ExprBuiltin.");

            return new ExprBuiltin(name.Value!, arg, argSchema, nameRange);
        }

        /// <summary>
        /// Serializes a <see cref="ExprBuiltin" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="exprBuiltin"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExprBuiltin exprBuiltin, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, exprBuiltin, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExprBuiltin" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="exprBuiltin"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, ExprBuiltin exprBuiltin, JsonSerializerOptions jsonSerializerOptions)
        {
            if (exprBuiltin.Name == null)
                throw new ArgumentNullException(nameof(exprBuiltin.Name), "Property is required for class ExprBuiltin.");

            if (exprBuiltin.ArgOption.IsSet && exprBuiltin.Arg == null)
                throw new ArgumentNullException(nameof(exprBuiltin.Arg), "Property is required for class ExprBuiltin.");

            if (exprBuiltin.NameRangeOption.IsSet && exprBuiltin.NameRange == null)
                throw new ArgumentNullException(nameof(exprBuiltin.NameRange), "Property is required for class ExprBuiltin.");

            writer.WriteString("name", exprBuiltin.Name);

            if (exprBuiltin.ArgOption.IsSet)
            {
                writer.WritePropertyName("arg");
                JsonSerializer.Serialize(writer, exprBuiltin.Arg, jsonSerializerOptions);
            }
            if (exprBuiltin.ArgSchemaOption.IsSet)
                if (exprBuiltin.ArgSchemaOption.Value != null)
                {
                    writer.WritePropertyName("argSchema");
                    JsonSerializer.Serialize(writer, exprBuiltin.ArgSchema, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("argSchema");
            if (exprBuiltin.NameRangeOption.IsSet)
            {
                writer.WritePropertyName("nameRange");
                JsonSerializer.Serialize(writer, exprBuiltin.NameRange, jsonSerializerOptions);
            }
        }
    }
}
