// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// Expr
    /// </summary>
    public partial class Expr : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Expr" /> class.
        /// </summary>
        /// <param name="access">access</param>
        /// <param name="base">base</param>
        /// <param name="builtin">builtin</param>
        /// <param name="interpolate">interpolate</param>
        /// <param name="keyRanges">keyRanges</param>
        /// <param name="list">list</param>
        /// <param name="literal">literal</param>
        /// <param name="object">object</param>
        /// <param name="range">range</param>
        /// <param name="schema">schema</param>
        /// <param name="symbol">symbol</param>
        [JsonConstructor]
        public Expr(Option<List<Access>?> access = default, Option<Expr?> @base = default, Option<ExprBuiltin?> builtin = default, Option<List<Interpolation>?> interpolate = default, Option<Dictionary<string, Range>?> keyRanges = default, Option<List<Expr>?> list = default, Option<Object?> literal = default, Option<Dictionary<string, Expr>?> @object = default, Option<Range?> range = default, Option<Object?> schema = default, Option<List<PropertyAccessor>?> symbol = default)
        {
            AccessOption = access;
            BaseOption = @base;
            BuiltinOption = builtin;
            InterpolateOption = interpolate;
            KeyRangesOption = keyRanges;
            ListOption = list;
            LiteralOption = literal;
            ObjectOption = @object;
            RangeOption = range;
            SchemaOption = schema;
            SymbolOption = symbol;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Access
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Access>?> AccessOption { get; private set; }

        /// <summary>
        /// Gets or Sets Access
        /// </summary>
        [JsonPropertyName("access")]
        public List<Access>? Access { get { return this.AccessOption; } set { this.AccessOption = new Option<List<Access>?>(value); } }

        /// <summary>
        /// Used to track the state of Base
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Expr?> BaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Base
        /// </summary>
        [JsonPropertyName("base")]
        public Expr? Base { get { return this.BaseOption; } set { this.BaseOption = new Option<Expr?>(value); } }

        /// <summary>
        /// Used to track the state of Builtin
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ExprBuiltin?> BuiltinOption { get; private set; }

        /// <summary>
        /// Gets or Sets Builtin
        /// </summary>
        [JsonPropertyName("builtin")]
        public ExprBuiltin? Builtin { get { return this.BuiltinOption; } set { this.BuiltinOption = new Option<ExprBuiltin?>(value); } }

        /// <summary>
        /// Used to track the state of Interpolate
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Interpolation>?> InterpolateOption { get; private set; }

        /// <summary>
        /// Gets or Sets Interpolate
        /// </summary>
        [JsonPropertyName("interpolate")]
        public List<Interpolation>? Interpolate { get { return this.InterpolateOption; } set { this.InterpolateOption = new Option<List<Interpolation>?>(value); } }

        /// <summary>
        /// Used to track the state of KeyRanges
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Range>?> KeyRangesOption { get; private set; }

        /// <summary>
        /// Gets or Sets KeyRanges
        /// </summary>
        [JsonPropertyName("keyRanges")]
        public Dictionary<string, Range>? KeyRanges { get { return this.KeyRangesOption; } set { this.KeyRangesOption = new Option<Dictionary<string, Range>?>(value); } }

        /// <summary>
        /// Used to track the state of List
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Expr>?> ListOption { get; private set; }

        /// <summary>
        /// Gets or Sets List
        /// </summary>
        [JsonPropertyName("list")]
        public List<Expr>? List { get { return this.ListOption; } set { this.ListOption = new Option<List<Expr>?>(value); } }

        /// <summary>
        /// Used to track the state of Literal
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> LiteralOption { get; private set; }

        /// <summary>
        /// Gets or Sets Literal
        /// </summary>
        [JsonPropertyName("literal")]
        public Object? Literal { get { return this.LiteralOption; } set { this.LiteralOption = new Option<Object?>(value); } }

        /// <summary>
        /// Used to track the state of Object
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Expr>?> ObjectOption { get; private set; }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [JsonPropertyName("object")]
        public Dictionary<string, Expr>? Object { get { return this.ObjectOption; } set { this.ObjectOption = new Option<Dictionary<string, Expr>?>(value); } }

        /// <summary>
        /// Used to track the state of Range
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Range?> RangeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [JsonPropertyName("range")]
        public Range? Range { get { return this.RangeOption; } set { this.RangeOption = new Option<Range?>(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> SchemaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [JsonPropertyName("schema")]
        public Object? Schema { get { return this.SchemaOption; } set { this.SchemaOption = new Option<Object?>(value); } }

        /// <summary>
        /// Used to track the state of Symbol
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PropertyAccessor>?> SymbolOption { get; private set; }

        /// <summary>
        /// Gets or Sets Symbol
        /// </summary>
        [JsonPropertyName("symbol")]
        public List<PropertyAccessor>? Symbol { get { return this.SymbolOption; } set { this.SymbolOption = new Option<List<PropertyAccessor>?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Expr {\n");
            sb.Append("  Access: ").Append(Access).Append("\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  Builtin: ").Append(Builtin).Append("\n");
            sb.Append("  Interpolate: ").Append(Interpolate).Append("\n");
            sb.Append("  KeyRanges: ").Append(KeyRanges).Append("\n");
            sb.Append("  List: ").Append(List).Append("\n");
            sb.Append("  Literal: ").Append(Literal).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Expr" />
    /// </summary>
    public class ExprJsonConverter : JsonConverter<Expr>
    {
        /// <summary>
        /// Deserializes json to <see cref="Expr" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Expr Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Access>?> access = default;
            Option<Expr?> varBase = default;
            Option<ExprBuiltin?> builtin = default;
            Option<List<Interpolation>?> interpolate = default;
            Option<Dictionary<string, Range>?> keyRanges = default;
            Option<List<Expr>?> list = default;
            Option<Object?> literal = default;
            Option<Dictionary<string, Expr>?> varObject = default;
            Option<Range?> range = default;
            Option<Object?> schema = default;
            Option<List<PropertyAccessor>?> symbol = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "access":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                access = new Option<List<Access>?>(JsonSerializer.Deserialize<List<Access>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "base":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varBase = new Option<Expr?>(JsonSerializer.Deserialize<Expr>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "builtin":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                builtin = new Option<ExprBuiltin?>(JsonSerializer.Deserialize<ExprBuiltin>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "interpolate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                interpolate = new Option<List<Interpolation>?>(JsonSerializer.Deserialize<List<Interpolation>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "keyRanges":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                keyRanges = new Option<Dictionary<string, Range>?>(JsonSerializer.Deserialize<Dictionary<string, Range>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "list":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                list = new Option<List<Expr>?>(JsonSerializer.Deserialize<List<Expr>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "literal":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                literal = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "object":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varObject = new Option<Dictionary<string, Expr>?>(JsonSerializer.Deserialize<Dictionary<string, Expr>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "range":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                range = new Option<Range?>(JsonSerializer.Deserialize<Range>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "schema":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                schema = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "symbol":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                symbol = new Option<List<PropertyAccessor>?>(JsonSerializer.Deserialize<List<PropertyAccessor>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (access.IsSet && access.Value == null)
                throw new ArgumentNullException(nameof(access), "Property is not nullable for class Expr.");

            if (varBase.IsSet && varBase.Value == null)
                throw new ArgumentNullException(nameof(varBase), "Property is not nullable for class Expr.");

            if (builtin.IsSet && builtin.Value == null)
                throw new ArgumentNullException(nameof(builtin), "Property is not nullable for class Expr.");

            if (interpolate.IsSet && interpolate.Value == null)
                throw new ArgumentNullException(nameof(interpolate), "Property is not nullable for class Expr.");

            if (keyRanges.IsSet && keyRanges.Value == null)
                throw new ArgumentNullException(nameof(keyRanges), "Property is not nullable for class Expr.");

            if (list.IsSet && list.Value == null)
                throw new ArgumentNullException(nameof(list), "Property is not nullable for class Expr.");

            if (varObject.IsSet && varObject.Value == null)
                throw new ArgumentNullException(nameof(varObject), "Property is not nullable for class Expr.");

            if (range.IsSet && range.Value == null)
                throw new ArgumentNullException(nameof(range), "Property is not nullable for class Expr.");

            if (symbol.IsSet && symbol.Value == null)
                throw new ArgumentNullException(nameof(symbol), "Property is not nullable for class Expr.");

            return new Expr(access, varBase, builtin, interpolate, keyRanges, list, literal, varObject, range, schema, symbol);
        }

        /// <summary>
        /// Serializes a <see cref="Expr" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="expr"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Expr expr, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, expr, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Expr" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="expr"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, Expr expr, JsonSerializerOptions jsonSerializerOptions)
        {
            if (expr.AccessOption.IsSet && expr.Access == null)
                throw new ArgumentNullException(nameof(expr.Access), "Property is required for class Expr.");

            if (expr.BaseOption.IsSet && expr.Base == null)
                throw new ArgumentNullException(nameof(expr.Base), "Property is required for class Expr.");

            if (expr.BuiltinOption.IsSet && expr.Builtin == null)
                throw new ArgumentNullException(nameof(expr.Builtin), "Property is required for class Expr.");

            if (expr.InterpolateOption.IsSet && expr.Interpolate == null)
                throw new ArgumentNullException(nameof(expr.Interpolate), "Property is required for class Expr.");

            if (expr.KeyRangesOption.IsSet && expr.KeyRanges == null)
                throw new ArgumentNullException(nameof(expr.KeyRanges), "Property is required for class Expr.");

            if (expr.ListOption.IsSet && expr.List == null)
                throw new ArgumentNullException(nameof(expr.List), "Property is required for class Expr.");

            if (expr.ObjectOption.IsSet && expr.Object == null)
                throw new ArgumentNullException(nameof(expr.Object), "Property is required for class Expr.");

            if (expr.RangeOption.IsSet && expr.Range == null)
                throw new ArgumentNullException(nameof(expr.Range), "Property is required for class Expr.");

            if (expr.SymbolOption.IsSet && expr.Symbol == null)
                throw new ArgumentNullException(nameof(expr.Symbol), "Property is required for class Expr.");

            if (expr.AccessOption.IsSet)
            {
                writer.WritePropertyName("access");
                JsonSerializer.Serialize(writer, expr.Access, jsonSerializerOptions);
            }
            if (expr.BaseOption.IsSet)
            {
                writer.WritePropertyName("base");
                JsonSerializer.Serialize(writer, expr.Base, jsonSerializerOptions);
            }
            if (expr.BuiltinOption.IsSet)
            {
                writer.WritePropertyName("builtin");
                JsonSerializer.Serialize(writer, expr.Builtin, jsonSerializerOptions);
            }
            if (expr.InterpolateOption.IsSet)
            {
                writer.WritePropertyName("interpolate");
                JsonSerializer.Serialize(writer, expr.Interpolate, jsonSerializerOptions);
            }
            if (expr.KeyRangesOption.IsSet)
            {
                writer.WritePropertyName("keyRanges");
                JsonSerializer.Serialize(writer, expr.KeyRanges, jsonSerializerOptions);
            }
            if (expr.ListOption.IsSet)
            {
                writer.WritePropertyName("list");
                JsonSerializer.Serialize(writer, expr.List, jsonSerializerOptions);
            }
            if (expr.LiteralOption.IsSet)
                if (expr.LiteralOption.Value != null)
                {
                    writer.WritePropertyName("literal");
                    JsonSerializer.Serialize(writer, expr.Literal, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("literal");
            if (expr.ObjectOption.IsSet)
            {
                writer.WritePropertyName("object");
                JsonSerializer.Serialize(writer, expr.Object, jsonSerializerOptions);
            }
            if (expr.RangeOption.IsSet)
            {
                writer.WritePropertyName("range");
                JsonSerializer.Serialize(writer, expr.Range, jsonSerializerOptions);
            }
            if (expr.SchemaOption.IsSet)
                if (expr.SchemaOption.Value != null)
                {
                    writer.WritePropertyName("schema");
                    JsonSerializer.Serialize(writer, expr.Schema, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("schema");
            if (expr.SymbolOption.IsSet)
            {
                writer.WritePropertyName("symbol");
                JsonSerializer.Serialize(writer, expr.Symbol, jsonSerializerOptions);
            }
        }
    }
}
