// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// ListEnvironmentTags
    /// </summary>
    public partial class ListEnvironmentTags : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListEnvironmentTags" /> class.
        /// </summary>
        /// <param name="nextToken">nextToken</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public ListEnvironmentTags(string nextToken, Dictionary<string, EnvironmentTag> tags)
        {
            NextToken = nextToken;
            Tags = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NextToken
        /// </summary>
        [JsonPropertyName("nextToken")]
        public string NextToken { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public Dictionary<string, EnvironmentTag> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListEnvironmentTags {\n");
            sb.Append("  NextToken: ").Append(NextToken).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListEnvironmentTags" />
    /// </summary>
    public class ListEnvironmentTagsJsonConverter : JsonConverter<ListEnvironmentTags>
    {
        /// <summary>
        /// Deserializes json to <see cref="ListEnvironmentTags" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListEnvironmentTags Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> nextToken = default;
            Option<Dictionary<string, EnvironmentTag>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "nextToken":
                            nextToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tags":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tags = new Option<Dictionary<string, EnvironmentTag>?>(JsonSerializer.Deserialize<Dictionary<string, EnvironmentTag>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!nextToken.IsSet)
                throw new ArgumentException("Property is required for class ListEnvironmentTags.", nameof(nextToken));

            if (!tags.IsSet)
                throw new ArgumentException("Property is required for class ListEnvironmentTags.", nameof(tags));

            if (nextToken.IsSet && nextToken.Value == null)
                throw new ArgumentNullException(nameof(nextToken), "Property is not nullable for class ListEnvironmentTags.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class ListEnvironmentTags.");

            return new ListEnvironmentTags(nextToken.Value!, tags.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ListEnvironmentTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listEnvironmentTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListEnvironmentTags listEnvironmentTags, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, listEnvironmentTags, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListEnvironmentTags" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listEnvironmentTags"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, ListEnvironmentTags listEnvironmentTags, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listEnvironmentTags.NextToken == null)
                throw new ArgumentNullException(nameof(listEnvironmentTags.NextToken), "Property is required for class ListEnvironmentTags.");

            if (listEnvironmentTags.Tags == null)
                throw new ArgumentNullException(nameof(listEnvironmentTags.Tags), "Property is required for class ListEnvironmentTags.");

            writer.WriteString("nextToken", listEnvironmentTags.NextToken);

            writer.WritePropertyName("tags");
            JsonSerializer.Serialize(writer, listEnvironmentTags.Tags, jsonSerializerOptions);
        }
    }
}
