// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// ModelEnvironment
    /// </summary>
    public partial class ModelEnvironment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelEnvironment" /> class.
        /// </summary>
        /// <param name="executionContext">executionContext</param>
        /// <param name="exprs">exprs</param>
        /// <param name="properties">properties</param>
        /// <param name="schema">schema</param>
        [JsonConstructor]
        public ModelEnvironment(Option<EvaluatedExecutionContext?> executionContext = default, Option<Dictionary<string, Expr>?> exprs = default, Option<Dictionary<string, Value>?> properties = default, Option<Object?> schema = default)
        {
            ExecutionContextOption = executionContext;
            ExprsOption = exprs;
            PropertiesOption = properties;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ExecutionContext
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EvaluatedExecutionContext?> ExecutionContextOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExecutionContext
        /// </summary>
        [JsonPropertyName("executionContext")]
        public EvaluatedExecutionContext? ExecutionContext { get { return this.ExecutionContextOption; } set { this.ExecutionContextOption = new Option<EvaluatedExecutionContext?>(value); } }

        /// <summary>
        /// Used to track the state of Exprs
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Expr>?> ExprsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Exprs
        /// </summary>
        [JsonPropertyName("exprs")]
        public Dictionary<string, Expr>? Exprs { get { return this.ExprsOption; } set { this.ExprsOption = new Option<Dictionary<string, Expr>?>(value); } }

        /// <summary>
        /// Used to track the state of Properties
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Value>?> PropertiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [JsonPropertyName("properties")]
        public Dictionary<string, Value>? Properties { get { return this.PropertiesOption; } set { this.PropertiesOption = new Option<Dictionary<string, Value>?>(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> SchemaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Schema
        /// </summary>
        [JsonPropertyName("schema")]
        public Object? Schema { get { return this.SchemaOption; } set { this.SchemaOption = new Option<Object?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModelEnvironment {\n");
            sb.Append("  ExecutionContext: ").Append(ExecutionContext).Append("\n");
            sb.Append("  Exprs: ").Append(Exprs).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ModelEnvironment" />
    /// </summary>
    public class ModelEnvironmentJsonConverter : JsonConverter<ModelEnvironment>
    {
        /// <summary>
        /// Deserializes json to <see cref="ModelEnvironment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ModelEnvironment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EvaluatedExecutionContext?> executionContext = default;
            Option<Dictionary<string, Expr>?> exprs = default;
            Option<Dictionary<string, Value>?> properties = default;
            Option<Object?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "executionContext":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                executionContext = new Option<EvaluatedExecutionContext?>(JsonSerializer.Deserialize<EvaluatedExecutionContext>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "exprs":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                exprs = new Option<Dictionary<string, Expr>?>(JsonSerializer.Deserialize<Dictionary<string, Expr>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "properties":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                properties = new Option<Dictionary<string, Value>?>(JsonSerializer.Deserialize<Dictionary<string, Value>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "schema":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                schema = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (executionContext.IsSet && executionContext.Value == null)
                throw new ArgumentNullException(nameof(executionContext), "Property is not nullable for class ModelEnvironment.");

            if (exprs.IsSet && exprs.Value == null)
                throw new ArgumentNullException(nameof(exprs), "Property is not nullable for class ModelEnvironment.");

            if (properties.IsSet && properties.Value == null)
                throw new ArgumentNullException(nameof(properties), "Property is not nullable for class ModelEnvironment.");

            return new ModelEnvironment(executionContext, exprs, properties, schema);
        }

        /// <summary>
        /// Serializes a <see cref="ModelEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="modelEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ModelEnvironment modelEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, modelEnvironment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ModelEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="modelEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, ModelEnvironment modelEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (modelEnvironment.ExecutionContextOption.IsSet && modelEnvironment.ExecutionContext == null)
                throw new ArgumentNullException(nameof(modelEnvironment.ExecutionContext), "Property is required for class ModelEnvironment.");

            if (modelEnvironment.ExprsOption.IsSet && modelEnvironment.Exprs == null)
                throw new ArgumentNullException(nameof(modelEnvironment.Exprs), "Property is required for class ModelEnvironment.");

            if (modelEnvironment.PropertiesOption.IsSet && modelEnvironment.Properties == null)
                throw new ArgumentNullException(nameof(modelEnvironment.Properties), "Property is required for class ModelEnvironment.");

            if (modelEnvironment.ExecutionContextOption.IsSet)
            {
                writer.WritePropertyName("executionContext");
                JsonSerializer.Serialize(writer, modelEnvironment.ExecutionContext, jsonSerializerOptions);
            }
            if (modelEnvironment.ExprsOption.IsSet)
            {
                writer.WritePropertyName("exprs");
                JsonSerializer.Serialize(writer, modelEnvironment.Exprs, jsonSerializerOptions);
            }
            if (modelEnvironment.PropertiesOption.IsSet)
            {
                writer.WritePropertyName("properties");
                JsonSerializer.Serialize(writer, modelEnvironment.Properties, jsonSerializerOptions);
            }
            if (modelEnvironment.SchemaOption.IsSet)
                if (modelEnvironment.SchemaOption.Value != null)
                {
                    writer.WritePropertyName("schema");
                    JsonSerializer.Serialize(writer, modelEnvironment.Schema, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("schema");
        }
    }
}
