// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// OpenEnvironment
    /// </summary>
    public partial class OpenEnvironment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenEnvironment" /> class.
        /// </summary>
        /// <param name="id">Open environment session identifier</param>
        /// <param name="diagnostics">diagnostics</param>
        [JsonConstructor]
        public OpenEnvironment(string id, Option<EnvironmentDiagnostics?> diagnostics = default)
        {
            Id = id;
            DiagnosticsOption = diagnostics;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Open environment session identifier
        /// </summary>
        /// <value>Open environment session identifier</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Used to track the state of Diagnostics
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EnvironmentDiagnostics?> DiagnosticsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Diagnostics
        /// </summary>
        [JsonPropertyName("diagnostics")]
        public EnvironmentDiagnostics? Diagnostics { get { return this.DiagnosticsOption; } set { this.DiagnosticsOption = new Option<EnvironmentDiagnostics?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OpenEnvironment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Diagnostics: ").Append(Diagnostics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OpenEnvironment" />
    /// </summary>
    public class OpenEnvironmentJsonConverter : JsonConverter<OpenEnvironment>
    {
        /// <summary>
        /// Deserializes json to <see cref="OpenEnvironment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OpenEnvironment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<EnvironmentDiagnostics?> diagnostics = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "diagnostics":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                diagnostics = new Option<EnvironmentDiagnostics?>(JsonSerializer.Deserialize<EnvironmentDiagnostics>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class OpenEnvironment.", nameof(id));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OpenEnvironment.");

            if (diagnostics.IsSet && diagnostics.Value == null)
                throw new ArgumentNullException(nameof(diagnostics), "Property is not nullable for class OpenEnvironment.");

            return new OpenEnvironment(id.Value!, diagnostics);
        }

        /// <summary>
        /// Serializes a <see cref="OpenEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OpenEnvironment openEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, openEnvironment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OpenEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, OpenEnvironment openEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (openEnvironment.Id == null)
                throw new ArgumentNullException(nameof(openEnvironment.Id), "Property is required for class OpenEnvironment.");

            if (openEnvironment.DiagnosticsOption.IsSet && openEnvironment.Diagnostics == null)
                throw new ArgumentNullException(nameof(openEnvironment.Diagnostics), "Property is required for class OpenEnvironment.");

            writer.WriteString("id", openEnvironment.Id);

            if (openEnvironment.DiagnosticsOption.IsSet)
            {
                writer.WritePropertyName("diagnostics");
                JsonSerializer.Serialize(writer, openEnvironment.Diagnostics, jsonSerializerOptions);
            }
        }
    }
}
