// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// OrgEnvironments
    /// </summary>
    public partial class OrgEnvironments : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrgEnvironments" /> class.
        /// </summary>
        /// <param name="environments">environments</param>
        /// <param name="nextToken">nextToken</param>
        [JsonConstructor]
        public OrgEnvironments(Option<List<OrgEnvironment>?> environments = default, Option<string?> nextToken = default)
        {
            EnvironmentsOption = environments;
            NextTokenOption = nextToken;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Environments
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<OrgEnvironment>?> EnvironmentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Environments
        /// </summary>
        [JsonPropertyName("environments")]
        public List<OrgEnvironment>? Environments { get { return this.EnvironmentsOption; } set { this.EnvironmentsOption = new Option<List<OrgEnvironment>?>(value); } }

        /// <summary>
        /// Used to track the state of NextToken
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NextTokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets NextToken
        /// </summary>
        [JsonPropertyName("nextToken")]
        public string? NextToken { get { return this.NextTokenOption; } set { this.NextTokenOption = new Option<string?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgEnvironments {\n");
            sb.Append("  Environments: ").Append(Environments).Append("\n");
            sb.Append("  NextToken: ").Append(NextToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrgEnvironments" />
    /// </summary>
    public class OrgEnvironmentsJsonConverter : JsonConverter<OrgEnvironments>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrgEnvironments" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrgEnvironments Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<OrgEnvironment>?> environments = default;
            Option<string?> nextToken = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "environments":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                environments = new Option<List<OrgEnvironment>?>(JsonSerializer.Deserialize<List<OrgEnvironment>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "nextToken":
                            nextToken = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (environments.IsSet && environments.Value == null)
                throw new ArgumentNullException(nameof(environments), "Property is not nullable for class OrgEnvironments.");

            if (nextToken.IsSet && nextToken.Value == null)
                throw new ArgumentNullException(nameof(nextToken), "Property is not nullable for class OrgEnvironments.");

            return new OrgEnvironments(environments, nextToken);
        }

        /// <summary>
        /// Serializes a <see cref="OrgEnvironments" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgEnvironments"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrgEnvironments orgEnvironments, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, orgEnvironments, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrgEnvironments" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgEnvironments"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, OrgEnvironments orgEnvironments, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orgEnvironments.EnvironmentsOption.IsSet && orgEnvironments.Environments == null)
                throw new ArgumentNullException(nameof(orgEnvironments.Environments), "Property is required for class OrgEnvironments.");

            if (orgEnvironments.NextTokenOption.IsSet && orgEnvironments.NextToken == null)
                throw new ArgumentNullException(nameof(orgEnvironments.NextToken), "Property is required for class OrgEnvironments.");

            if (orgEnvironments.EnvironmentsOption.IsSet)
            {
                writer.WritePropertyName("environments");
                JsonSerializer.Serialize(writer, orgEnvironments.Environments, jsonSerializerOptions);
            }
            if (orgEnvironments.NextTokenOption.IsSet)
                writer.WriteString("nextToken", orgEnvironments.NextToken);
        }
    }
}
