// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// OrgEnvironment
    /// </summary>
    public partial class OrgEnvironment : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrgEnvironment" /> class.
        /// </summary>
        /// <param name="created">created</param>
        /// <param name="modified">modified</param>
        /// <param name="name">name</param>
        /// <param name="project">project</param>
        /// <param name="organization">organization</param>
        [JsonConstructor]
        public OrgEnvironment(string created, string modified, string name, string project, Option<string?> organization = default)
        {
            Created = created;
            Modified = modified;
            Name = name;
            Project = project;
            OrganizationOption = organization;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [JsonPropertyName("created")]
        public string Created { get; set; }

        /// <summary>
        /// Gets or Sets Modified
        /// </summary>
        [JsonPropertyName("modified")]
        public string Modified { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Project
        /// </summary>
        [JsonPropertyName("project")]
        public string Project { get; set; }

        /// <summary>
        /// Used to track the state of Organization
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrganizationOption { get; private set; }

        /// <summary>
        /// Gets or Sets Organization
        /// </summary>
        [JsonPropertyName("organization")]
        public string? Organization { get { return this.OrganizationOption; } set { this.OrganizationOption = new Option<string?>(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrgEnvironment {\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Project: ").Append(Project).Append("\n");
            sb.Append("  Organization: ").Append(Organization).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrgEnvironment" />
    /// </summary>
    public class OrgEnvironmentJsonConverter : JsonConverter<OrgEnvironment>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrgEnvironment" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrgEnvironment Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> created = default;
            Option<string?> modified = default;
            Option<string?> name = default;
            Option<string?> project = default;
            Option<string?> organization = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "created":
                            created = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "modified":
                            modified = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "project":
                            project = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organization":
                            organization = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!created.IsSet)
                throw new ArgumentException("Property is required for class OrgEnvironment.", nameof(created));

            if (!modified.IsSet)
                throw new ArgumentException("Property is required for class OrgEnvironment.", nameof(modified));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class OrgEnvironment.", nameof(name));

            if (!project.IsSet)
                throw new ArgumentException("Property is required for class OrgEnvironment.", nameof(project));

            if (created.IsSet && created.Value == null)
                throw new ArgumentNullException(nameof(created), "Property is not nullable for class OrgEnvironment.");

            if (modified.IsSet && modified.Value == null)
                throw new ArgumentNullException(nameof(modified), "Property is not nullable for class OrgEnvironment.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class OrgEnvironment.");

            if (project.IsSet && project.Value == null)
                throw new ArgumentNullException(nameof(project), "Property is not nullable for class OrgEnvironment.");

            if (organization.IsSet && organization.Value == null)
                throw new ArgumentNullException(nameof(organization), "Property is not nullable for class OrgEnvironment.");

            return new OrgEnvironment(created.Value!, modified.Value!, name.Value!, project.Value!, organization);
        }

        /// <summary>
        /// Serializes a <see cref="OrgEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrgEnvironment orgEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, orgEnvironment, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrgEnvironment" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orgEnvironment"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, OrgEnvironment orgEnvironment, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orgEnvironment.Created == null)
                throw new ArgumentNullException(nameof(orgEnvironment.Created), "Property is required for class OrgEnvironment.");

            if (orgEnvironment.Modified == null)
                throw new ArgumentNullException(nameof(orgEnvironment.Modified), "Property is required for class OrgEnvironment.");

            if (orgEnvironment.Name == null)
                throw new ArgumentNullException(nameof(orgEnvironment.Name), "Property is required for class OrgEnvironment.");

            if (orgEnvironment.Project == null)
                throw new ArgumentNullException(nameof(orgEnvironment.Project), "Property is required for class OrgEnvironment.");

            if (orgEnvironment.OrganizationOption.IsSet && orgEnvironment.Organization == null)
                throw new ArgumentNullException(nameof(orgEnvironment.Organization), "Property is required for class OrgEnvironment.");

            writer.WriteString("created", orgEnvironment.Created);

            writer.WriteString("modified", orgEnvironment.Modified);

            writer.WriteString("name", orgEnvironment.Name);

            writer.WriteString("project", orgEnvironment.Project);

            if (orgEnvironment.OrganizationOption.IsSet)
                writer.WriteString("organization", orgEnvironment.Organization);
        }
    }
}
