// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// Pos
    /// </summary>
    public partial class Pos : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pos" /> class.
        /// </summary>
        /// <param name="byte">Byte is the byte offset into the file where the indicated position begins.</param>
        /// <param name="column">Column is the source code column where this position points. Columns are counted in visual cells starting at 1, and are incremented roughly per grapheme cluster encountered.</param>
        /// <param name="line">Line is the source code line where this position points. Lines are counted starting at 1 and incremented for each newline character encountered.</param>
        [JsonConstructor]
        public Pos(int @byte, int column, int line)
        {
            Byte = @byte;
            Column = column;
            Line = line;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Byte is the byte offset into the file where the indicated position begins.
        /// </summary>
        /// <value>Byte is the byte offset into the file where the indicated position begins.</value>
        [JsonPropertyName("byte")]
        public int Byte { get; set; }

        /// <summary>
        /// Column is the source code column where this position points. Columns are counted in visual cells starting at 1, and are incremented roughly per grapheme cluster encountered.
        /// </summary>
        /// <value>Column is the source code column where this position points. Columns are counted in visual cells starting at 1, and are incremented roughly per grapheme cluster encountered.</value>
        [JsonPropertyName("column")]
        public int Column { get; set; }

        /// <summary>
        /// Line is the source code line where this position points. Lines are counted starting at 1 and incremented for each newline character encountered.
        /// </summary>
        /// <value>Line is the source code line where this position points. Lines are counted starting at 1 and incremented for each newline character encountered.</value>
        [JsonPropertyName("line")]
        public int Line { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Pos {\n");
            sb.Append("  Byte: ").Append(Byte).Append("\n");
            sb.Append("  Column: ").Append(Column).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Pos" />
    /// </summary>
    public class PosJsonConverter : JsonConverter<Pos>
    {
        /// <summary>
        /// Deserializes json to <see cref="Pos" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Pos Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> varByte = default;
            Option<int?> column = default;
            Option<int?> line = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "byte":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varByte = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "column":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                column = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "line":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                line = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!varByte.IsSet)
                throw new ArgumentException("Property is required for class Pos.", nameof(varByte));

            if (!column.IsSet)
                throw new ArgumentException("Property is required for class Pos.", nameof(column));

            if (!line.IsSet)
                throw new ArgumentException("Property is required for class Pos.", nameof(line));

            if (varByte.IsSet && varByte.Value == null)
                throw new ArgumentNullException(nameof(varByte), "Property is not nullable for class Pos.");

            if (column.IsSet && column.Value == null)
                throw new ArgumentNullException(nameof(column), "Property is not nullable for class Pos.");

            if (line.IsSet && line.Value == null)
                throw new ArgumentNullException(nameof(line), "Property is not nullable for class Pos.");

            return new Pos(varByte.Value!.Value!, column.Value!.Value!, line.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Pos" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pos"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Pos pos, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, pos, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Pos" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="pos"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, Pos pos, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("byte", pos.Byte);

            writer.WriteNumber("column", pos.Column);

            writer.WriteNumber("line", pos.Line);
        }
    }
}
