// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// Trace
    /// </summary>
    public partial class Trace : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Trace" /> class.
        /// </summary>
        /// <param name="base">base</param>
        /// <param name="def">def</param>
        [JsonConstructor]
        public Trace(Option<Value?> @base = default, Option<Range?> def = default)
        {
            BaseOption = @base;
            DefOption = def;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Base
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Value?> BaseOption { get; private set; }

        /// <summary>
        /// Gets or Sets Base
        /// </summary>
        [JsonPropertyName("base")]
        public Value? Base { get { return this.BaseOption; } set { this.BaseOption = new Option<Value?>(value); } }

        /// <summary>
        /// Used to track the state of Def
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Range?> DefOption { get; private set; }

        /// <summary>
        /// Gets or Sets Def
        /// </summary>
        [JsonPropertyName("def")]
        public Range? Def { get { return this.DefOption; } set { this.DefOption = new Option<Range?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Trace {\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  Def: ").Append(Def).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Trace" />
    /// </summary>
    public class TraceJsonConverter : JsonConverter<Trace>
    {
        /// <summary>
        /// Deserializes json to <see cref="Trace" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Trace Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Value?> varBase = default;
            Option<Range?> def = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "base":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varBase = new Option<Value?>(JsonSerializer.Deserialize<Value>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "def":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                def = new Option<Range?>(JsonSerializer.Deserialize<Range>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (varBase.IsSet && varBase.Value == null)
                throw new ArgumentNullException(nameof(varBase), "Property is not nullable for class Trace.");

            if (def.IsSet && def.Value == null)
                throw new ArgumentNullException(nameof(def), "Property is not nullable for class Trace.");

            return new Trace(varBase, def);
        }

        /// <summary>
        /// Serializes a <see cref="Trace" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trace"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Trace trace, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, trace, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Trace" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trace"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, Trace trace, JsonSerializerOptions jsonSerializerOptions)
        {
            if (trace.BaseOption.IsSet && trace.Base == null)
                throw new ArgumentNullException(nameof(trace.Base), "Property is required for class Trace.");

            if (trace.DefOption.IsSet && trace.Def == null)
                throw new ArgumentNullException(nameof(trace.Def), "Property is required for class Trace.");

            if (trace.BaseOption.IsSet)
            {
                writer.WritePropertyName("base");
                JsonSerializer.Serialize(writer, trace.Base, jsonSerializerOptions);
            }
            if (trace.DefOption.IsSet)
            {
                writer.WritePropertyName("def");
                JsonSerializer.Serialize(writer, trace.Def, jsonSerializerOptions);
            }
        }
    }
}
