// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// UpdateEnvironmentRevisionTag
    /// </summary>
    public partial class UpdateEnvironmentRevisionTag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEnvironmentRevisionTag" /> class.
        /// </summary>
        /// <param name="revision">revision</param>
        [JsonConstructor]
        public UpdateEnvironmentRevisionTag(int revision)
        {
            Revision = revision;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Revision
        /// </summary>
        [JsonPropertyName("revision")]
        public int Revision { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEnvironmentRevisionTag {\n");
            sb.Append("  Revision: ").Append(Revision).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateEnvironmentRevisionTag" />
    /// </summary>
    public class UpdateEnvironmentRevisionTagJsonConverter : JsonConverter<UpdateEnvironmentRevisionTag>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateEnvironmentRevisionTag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateEnvironmentRevisionTag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> revision = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "revision":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                revision = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!revision.IsSet)
                throw new ArgumentException("Property is required for class UpdateEnvironmentRevisionTag.", nameof(revision));

            if (revision.IsSet && revision.Value == null)
                throw new ArgumentNullException(nameof(revision), "Property is not nullable for class UpdateEnvironmentRevisionTag.");

            return new UpdateEnvironmentRevisionTag(revision.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateEnvironmentRevisionTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentRevisionTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateEnvironmentRevisionTag updateEnvironmentRevisionTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, updateEnvironmentRevisionTag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateEnvironmentRevisionTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentRevisionTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, UpdateEnvironmentRevisionTag updateEnvironmentRevisionTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteNumber("revision", updateEnvironmentRevisionTag.Revision);
        }
    }
}
