// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// UpdateEnvironmentTagCurrentTag
    /// </summary>
    public partial class UpdateEnvironmentTagCurrentTag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEnvironmentTagCurrentTag" /> class.
        /// </summary>
        /// <param name="value">value</param>
        [JsonConstructor]
        public UpdateEnvironmentTagCurrentTag(string value)
        {
            Value = value;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEnvironmentTagCurrentTag {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateEnvironmentTagCurrentTag" />
    /// </summary>
    public class UpdateEnvironmentTagCurrentTagJsonConverter : JsonConverter<UpdateEnvironmentTagCurrentTag>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateEnvironmentTagCurrentTag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateEnvironmentTagCurrentTag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> value = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class UpdateEnvironmentTagCurrentTag.", nameof(value));

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class UpdateEnvironmentTagCurrentTag.");

            return new UpdateEnvironmentTagCurrentTag(value.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateEnvironmentTagCurrentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentTagCurrentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateEnvironmentTagCurrentTag updateEnvironmentTagCurrentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, updateEnvironmentTagCurrentTag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateEnvironmentTagCurrentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentTagCurrentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, UpdateEnvironmentTagCurrentTag updateEnvironmentTagCurrentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateEnvironmentTagCurrentTag.Value == null)
                throw new ArgumentNullException(nameof(updateEnvironmentTagCurrentTag.Value), "Property is required for class UpdateEnvironmentTagCurrentTag.");

            writer.WriteString("value", updateEnvironmentTagCurrentTag.Value);
        }
    }
}
