// <auto-generated>
// Copyright 2026, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// UpdateEnvironmentTag
    /// </summary>
    public partial class UpdateEnvironmentTag : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateEnvironmentTag" /> class.
        /// </summary>
        /// <param name="currentTag">currentTag</param>
        /// <param name="newTag">newTag</param>
        [JsonConstructor]
        public UpdateEnvironmentTag(UpdateEnvironmentTagCurrentTag currentTag, UpdateEnvironmentTagNewTag newTag)
        {
            CurrentTag = currentTag;
            NewTag = newTag;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CurrentTag
        /// </summary>
        [JsonPropertyName("currentTag")]
        public UpdateEnvironmentTagCurrentTag CurrentTag { get; set; }

        /// <summary>
        /// Gets or Sets NewTag
        /// </summary>
        [JsonPropertyName("newTag")]
        public UpdateEnvironmentTagNewTag NewTag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateEnvironmentTag {\n");
            sb.Append("  CurrentTag: ").Append(CurrentTag).Append("\n");
            sb.Append("  NewTag: ").Append(NewTag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateEnvironmentTag" />
    /// </summary>
    public class UpdateEnvironmentTagJsonConverter : JsonConverter<UpdateEnvironmentTag>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateEnvironmentTag" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateEnvironmentTag Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<UpdateEnvironmentTagCurrentTag?> currentTag = default;
            Option<UpdateEnvironmentTagNewTag?> newTag = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "currentTag":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                currentTag = new Option<UpdateEnvironmentTagCurrentTag?>(JsonSerializer.Deserialize<UpdateEnvironmentTagCurrentTag>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "newTag":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                newTag = new Option<UpdateEnvironmentTagNewTag?>(JsonSerializer.Deserialize<UpdateEnvironmentTagNewTag>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!currentTag.IsSet)
                throw new ArgumentException("Property is required for class UpdateEnvironmentTag.", nameof(currentTag));

            if (!newTag.IsSet)
                throw new ArgumentException("Property is required for class UpdateEnvironmentTag.", nameof(newTag));

            if (currentTag.IsSet && currentTag.Value == null)
                throw new ArgumentNullException(nameof(currentTag), "Property is not nullable for class UpdateEnvironmentTag.");

            if (newTag.IsSet && newTag.Value == null)
                throw new ArgumentNullException(nameof(newTag), "Property is not nullable for class UpdateEnvironmentTag.");

            return new UpdateEnvironmentTag(currentTag.Value!, newTag.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateEnvironmentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateEnvironmentTag updateEnvironmentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, updateEnvironmentTag, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateEnvironmentTag" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateEnvironmentTag"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, UpdateEnvironmentTag updateEnvironmentTag, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateEnvironmentTag.CurrentTag == null)
                throw new ArgumentNullException(nameof(updateEnvironmentTag.CurrentTag), "Property is required for class UpdateEnvironmentTag.");

            if (updateEnvironmentTag.NewTag == null)
                throw new ArgumentNullException(nameof(updateEnvironmentTag.NewTag), "Property is required for class UpdateEnvironmentTag.");

            writer.WritePropertyName("currentTag");
            JsonSerializer.Serialize(writer, updateEnvironmentTag.CurrentTag, jsonSerializerOptions);
            writer.WritePropertyName("newTag");
            JsonSerializer.Serialize(writer, updateEnvironmentTag.NewTag, jsonSerializerOptions);
        }
    }
}
