// <auto-generated>
// Copyright 2024, Pulumi Corporation.  All rights reserved.
/*
ESC (Environments, Secrets, Config) API

Pulumi ESC allows you to compose and manage hierarchical collections of configuration and secrets and consume them in various ways.

API version: 0.1.0
*/


#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Pulumi.Esc.Sdk.Client;

namespace Pulumi.Esc.Sdk.Model
{
    /// <summary>
    /// Value
    /// </summary>
    public partial class Value : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Value" /> class.
        /// </summary>
        /// <param name="trace">trace</param>
        /// <param name="secret">secret</param>
        /// <param name="unknown">unknown</param>
        /// <param name="varValue">varValue</param>
        [JsonConstructor]
        public Value(Trace trace, Option<bool?> secret = default, Option<bool?> unknown = default, Object? varValue = default)
        {
            Trace = trace;
            SecretOption = secret;
            UnknownOption = unknown;
            VarValue = varValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Trace
        /// </summary>
        [JsonPropertyName("trace")]
        public Trace Trace { get; set; }

        /// <summary>
        /// Used to track the state of Secret
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SecretOption { get; private set; }

        /// <summary>
        /// Gets or Sets Secret
        /// </summary>
        [JsonPropertyName("secret")]
        public bool? Secret { get { return this.SecretOption; } set { this.SecretOption = new Option<bool?>(value); } }

        /// <summary>
        /// Used to track the state of Unknown
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> UnknownOption { get; private set; }

        /// <summary>
        /// Gets or Sets Unknown
        /// </summary>
        [JsonPropertyName("unknown")]
        public bool? Unknown { get { return this.UnknownOption; } set { this.UnknownOption = new Option<bool?>(value); } }

        /// <summary>
        /// Gets or Sets VarValue
        /// </summary>
        [JsonPropertyName("value")]
        public Object? VarValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Value {\n");
            sb.Append("  Trace: ").Append(Trace).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("  Unknown: ").Append(Unknown).Append("\n");
            sb.Append("  VarValue: ").Append(VarValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Value" />
    /// </summary>
    public class ValueJsonConverter : JsonConverter<Value>
    {
        /// <summary>
        /// Deserializes json to <see cref="Value" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Value Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Trace?> trace = default;
            Option<bool?> secret = default;
            Option<bool?> unknown = default;
            Option<Object?> varValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "trace":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                trace = new Option<Trace?>(JsonSerializer.Deserialize<Trace>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "secret":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                secret = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "unknown":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                unknown = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "value":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varValue = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!trace.IsSet)
                throw new ArgumentException("Property is required for class Value.", nameof(trace));

            // Note: varValue is marked required in the swagger spec but the API
            // returns Value objects without a "value" field (e.g. when unknown=true).
            // Do not enforce it as required here.

            if (trace.IsSet && trace.Value == null)
                throw new ArgumentNullException(nameof(trace), "Property is not nullable for class Value.");

            if (secret.IsSet && secret.Value == null)
                throw new ArgumentNullException(nameof(secret), "Property is not nullable for class Value.");

            if (unknown.IsSet && unknown.Value == null)
                throw new ArgumentNullException(nameof(unknown), "Property is not nullable for class Value.");

            return new Value(trace.Value!, secret, unknown, varValue.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Value" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="value"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Value value, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, value, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Value" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="value"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, Value value, JsonSerializerOptions jsonSerializerOptions)
        {
            if (value.Trace == null)
                throw new ArgumentNullException(nameof(value.Trace), "Property is required for class Value.");

            writer.WritePropertyName("trace");
            JsonSerializer.Serialize(writer, value.Trace, jsonSerializerOptions);
            if (value.SecretOption.IsSet)
                writer.WriteBoolean("secret", value.SecretOption.Value!.Value);

            if (value.UnknownOption.IsSet)
                writer.WriteBoolean("unknown", value.UnknownOption.Value!.Value);

            if (value.VarValue != null)
            {
                writer.WritePropertyName("value");
                JsonSerializer.Serialize(writer, value.VarValue, jsonSerializerOptions);
            }
            else
                writer.WriteNull("value");
        }
    }
}
