// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Byepackage
{
    public static class DoGoodbyeWorld
    {
        public static Task<DoGoodbyeWorldResult> InvokeAsync(DoGoodbyeWorldArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<DoGoodbyeWorldResult>("byepackage:index:doGoodbyeWorld", args ?? new DoGoodbyeWorldArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<DoGoodbyeWorldResult> Invoke(DoGoodbyeWorldInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<DoGoodbyeWorldResult>("byepackage:index:doGoodbyeWorld", args ?? new DoGoodbyeWorldInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());

        public static Output<DoGoodbyeWorldResult> Invoke(DoGoodbyeWorldInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<DoGoodbyeWorldResult>("byepackage:index:doGoodbyeWorld", args ?? new DoGoodbyeWorldInvokeArgs(), options.WithDefaults(), Utilities.PackageParameterization());
    }


    public sealed class DoGoodbyeWorldArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public DoGoodbyeWorldArgs()
        {
        }
        public static new DoGoodbyeWorldArgs Empty => new DoGoodbyeWorldArgs();
    }

    public sealed class DoGoodbyeWorldInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public DoGoodbyeWorldInvokeArgs()
        {
        }
        public static new DoGoodbyeWorldInvokeArgs Empty => new DoGoodbyeWorldInvokeArgs();
    }


    [OutputType]
    public sealed class DoGoodbyeWorldResult
    {
        public readonly string Output;

        [OutputConstructor]
        private DoGoodbyeWorldResult(string output)
        {
            Output = output;
        }
    }
}
