// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SimpleInvokeWithScalarReturn
{
    public static class MyInvokeScalar
    {
        public static Task<bool> InvokeAsync(MyInvokeScalarArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingleAsync<bool>("simple-invoke-with-scalar-return:index:myInvokeScalar", args ?? new MyInvokeScalarArgs(), options.WithDefaults());

        public static Output<bool> Invoke(MyInvokeScalarInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingle<bool>("simple-invoke-with-scalar-return:index:myInvokeScalar", args ?? new MyInvokeScalarInvokeArgs(), options.WithDefaults());

        public static Output<bool> Invoke(MyInvokeScalarInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.InvokeSingle<bool>("simple-invoke-with-scalar-return:index:myInvokeScalar", args ?? new MyInvokeScalarInvokeArgs(), options.WithDefaults());
    }


    public sealed class MyInvokeScalarArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public MyInvokeScalarArgs()
        {
        }
        public static new MyInvokeScalarArgs Empty => new MyInvokeScalarArgs();
    }

    public sealed class MyInvokeScalarInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public MyInvokeScalarInvokeArgs()
        {
        }
        public static new MyInvokeScalarInvokeArgs Empty => new MyInvokeScalarInvokeArgs();
    }
}
