// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Plain.Inputs
{

    public sealed class DataArgs : global::Pulumi.ResourceArgs
    {
        [Input("boolArray", required: true)]
        private List<bool>? _boolArray;
        public List<bool> BoolArray
        {
            get => _boolArray ?? (_boolArray = new List<bool>());
            set => _boolArray = value;
        }

        [Input("boolean", required: true)]
        public bool Boolean { get; set; }

        [Input("float", required: true)]
        public double Float { get; set; }

        [Input("innerData", required: true)]
        public Inputs.InnerDataArgs InnerData { get; set; } = null!;

        [Input("integer", required: true)]
        public int Integer { get; set; }

        [Input("string", required: true)]
        public string String { get; set; } = null!;

        [Input("stringMap", required: true)]
        private Dictionary<string, string>? _stringMap;
        public Dictionary<string, string> StringMap
        {
            get => _stringMap ?? (_stringMap = new Dictionary<string, string>());
            set => _stringMap = value;
        }

        public DataArgs()
        {
        }
        public static new DataArgs Empty => new DataArgs();
    }
}
