[env]
PULUMI_ROOT = "{{config_root}}/.root"

_.path = [
  "{{env.PULUMI_ROOT}}/bin",
]

[tools]
changie = "1.24.2"
go = "1.25"
gofumpt = "0.9.1"
golangci-lint = "2.9.0"
gotestsum = "latest"
"github:pulumi/pulumi" = "latest"
"vfox:dotnet" = { version = "8.0", postinstall = "powershell -File {{config_root}}/scripts/install-dotnet-runtime.ps1 || bash {{config_root}}/scripts/install-dotnet-runtime.sh" }
