<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="build\GitSync.fs" />
    <Compile Include="build\Nuget.fs" />
    <Compile Include="build\PulumiSdkVersion.fs" />
    <Compile Include="build\Publish.fs" />
    <Compile Include="build\Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" />
    <PackageReference Include="Fake.Core.Environment" />
    <PackageReference Include="Fake.Core.Target" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

</Project>