<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="8.10.0"/>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1"/>
  </ItemGroup>
</Project>