// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Enum.Outputs
{

    [OutputType]
    public sealed class Holder
    {
        public readonly Pulumi.Enum.StringEnum? Color;
        public readonly Pulumi.Enum.IntEnum? Size;

        [OutputConstructor]
        private Holder(
            Pulumi.Enum.StringEnum? color,

            Pulumi.Enum.IntEnum? size)
        {
            Color = color;
            Size = size;
        }
    }
}
