// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Selfref
{
    [SelfrefResourceType("selfref:index:Node")]
    public partial class Node : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Create a Node resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Node(string name, NodeArgs? args = null, CustomResourceOptions? options = null)
            : base("selfref:index:Node", name, args ?? new NodeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Node(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("selfref:index:Node", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Node resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Node Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Node(name, id, options);
        }
    }

    public sealed class NodeArgs : global::Pulumi.ResourceArgs
    {
        [Input("namedParents")]
        private InputMap<Pulumi.Selfref.Node>? _namedParents;
        public InputMap<Pulumi.Selfref.Node> NamedParents
        {
            get => _namedParents ?? (_namedParents = new InputMap<Pulumi.Selfref.Node>());
            set => _namedParents = value;
        }

        [Input("parent")]
        public Input<Pulumi.Selfref.Node>? Parent { get; set; }

        [Input("parentOrName")]
        public InputUnion<Pulumi.Selfref.Node, string>? ParentOrName { get; set; }

        [Input("parents")]
        private InputList<Pulumi.Selfref.Node>? _parents;
        public InputList<Pulumi.Selfref.Node> Parents
        {
            get => _parents ?? (_parents = new InputList<Pulumi.Selfref.Node>());
            set => _parents = value;
        }

        public NodeArgs()
        {
        }
        public static new NodeArgs Empty => new NodeArgs();
    }
}
