// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Outputs
{

    [OutputType]
    public sealed class Variant8
    {
        public readonly string DiscriminantKind;
        public readonly string? Payload;
        public readonly int? Size;

        [OutputConstructor]
        private Variant8(
            string discriminantKind,

            string? payload,

            int? size)
        {
            DiscriminantKind = discriminantKind;
            Payload = payload;
            Size = size;
        }
    }
}
