// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Outputs
{

    [OutputType]
    public sealed class Variant5
    {
        public readonly string DiscriminantKind;
        public readonly string? Label;
        public readonly string? Payload;

        [OutputConstructor]
        private Variant5(
            string discriminantKind,

            string? label,

            string? payload)
        {
            DiscriminantKind = discriminantKind;
            Label = label;
            Payload = payload;
        }
    }
}
