// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Outputs
{

    [OutputType]
    public sealed class Variant4
    {
        public readonly string DiscriminantKind;
        public readonly bool? Enabled;
        public readonly string? Payload;

        [OutputConstructor]
        private Variant4(
            string discriminantKind,

            bool? enabled,

            string? payload)
        {
            DiscriminantKind = discriminantKind;
            Enabled = enabled;
            Payload = payload;
        }
    }
}
