// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Outputs
{

    [OutputType]
    public sealed class Variant3
    {
        public readonly int? Count;
        public readonly string DiscriminantKind;
        public readonly string? Payload;

        [OutputConstructor]
        private Variant3(
            int? count,

            string discriminantKind,

            string? payload)
        {
            Count = count;
            DiscriminantKind = discriminantKind;
            Payload = payload;
        }
    }
}
