// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Component
{
    /// <summary>
    /// A component resource that accepts an input that is used to create a child custom resource. A reference to this child custom resource is returned.
    /// </summary>
    [ComponentResourceType("component:index:ComponentCustomRefOutput")]
    public partial class ComponentCustomRefOutput : global::Pulumi.ComponentResource
    {
        [Output("ref")]
        public Output<Pulumi.Component.Custom> Ref { get; private set; } = null!;

        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a ComponentCustomRefOutput resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ComponentCustomRefOutput(string name, ComponentCustomRefOutputArgs args, ComponentResourceOptions? options = null)
            : base("component:index:ComponentCustomRefOutput", name, args ?? new ComponentCustomRefOutputArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ComponentCustomRefOutputArgs : global::Pulumi.ResourceArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ComponentCustomRefOutputArgs()
        {
        }
        public static new ComponentCustomRefOutputArgs Empty => new ComponentCustomRefOutputArgs();
    }
}
