// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Component
{
    public static class Identity
    {
        /// <summary>
        /// Returns its input unchanged.
        /// </summary>
        public static Task<IdentityResult> InvokeAsync(IdentityArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<IdentityResult>("component:index:identity", args ?? new IdentityArgs(), options.WithDefaults());

        /// <summary>
        /// Returns its input unchanged.
        /// </summary>
        public static Output<IdentityResult> Invoke(IdentityInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<IdentityResult>("component:index:identity", args ?? new IdentityInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Returns its input unchanged.
        /// </summary>
        public static Output<IdentityResult> Invoke(IdentityInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<IdentityResult>("component:index:identity", args ?? new IdentityInvokeArgs(), options.WithDefaults());
    }


    public sealed class IdentityArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public string Input { get; set; } = null!;

        public IdentityArgs()
        {
        }
        public static new IdentityArgs Empty => new IdentityArgs();
    }

    public sealed class IdentityInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public IdentityInvokeArgs()
        {
        }
        public static new IdentityInvokeArgs Empty => new IdentityInvokeArgs();
    }


    [OutputType]
    public sealed class IdentityResult
    {
        public readonly string Result;

        [OutputConstructor]
        private IdentityResult(string result)
        {
            Result = result;
        }
    }
}
