// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ModuleFormat
{
    public static class ConcatWorld
    {
        public static Task<ConcatWorldResult> InvokeAsync(ConcatWorldArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ConcatWorldResult>("module-format:index_concatWorld:concatWorld", args ?? new ConcatWorldArgs(), options.WithDefaults());

        public static Output<ConcatWorldResult> Invoke(ConcatWorldInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ConcatWorldResult>("module-format:index_concatWorld:concatWorld", args ?? new ConcatWorldInvokeArgs(), options.WithDefaults());

        public static Output<ConcatWorldResult> Invoke(ConcatWorldInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ConcatWorldResult>("module-format:index_concatWorld:concatWorld", args ?? new ConcatWorldInvokeArgs(), options.WithDefaults());
    }


    public sealed class ConcatWorldArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public ConcatWorldArgs()
        {
        }
        public static new ConcatWorldArgs Empty => new ConcatWorldArgs();
    }

    public sealed class ConcatWorldInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ConcatWorldInvokeArgs()
        {
        }
        public static new ConcatWorldInvokeArgs Empty => new ConcatWorldInvokeArgs();
    }


    [OutputType]
    public sealed class ConcatWorldResult
    {
        public readonly string Result;

        [OutputConstructor]
        private ConcatWorldResult(string result)
        {
            Result = result;
        }
    }
}
