// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnion
{
    [DiscriminatedUnionResourceType("discriminated-union:index:Example")]
    public partial class Example : global::Pulumi.CustomResource
    {
        [Output("arrayOfUnionOf")]
        public Output<ImmutableArray<Union<Outputs.VariantOne, Outputs.VariantTwo>>> ArrayOfUnionOf { get; private set; } = null!;

        [Output("unionOf")]
        public Output<Union<Outputs.VariantOne, Outputs.VariantTwo>?> UnionOf { get; private set; } = null!;


        /// <summary>
        /// Create a Example resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Example(string name, ExampleArgs? args = null, CustomResourceOptions? options = null)
            : base("discriminated-union:index:Example", name, args ?? new ExampleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Example(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("discriminated-union:index:Example", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Example resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Example Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Example(name, id, options);
        }
    }

    public sealed class ExampleArgs : global::Pulumi.ResourceArgs
    {
        [Input("arrayOfUnionOf")]
        private InputList<Union<Inputs.VariantOneArgs, Inputs.VariantTwoArgs>>? _arrayOfUnionOf;
        public InputList<Union<Inputs.VariantOneArgs, Inputs.VariantTwoArgs>> ArrayOfUnionOf
        {
            get => _arrayOfUnionOf ?? (_arrayOfUnionOf = new InputList<Union<Inputs.VariantOneArgs, Inputs.VariantTwoArgs>>());
            set => _arrayOfUnionOf = value;
        }

        [Input("unionOf")]
        public InputUnion<Inputs.VariantOneArgs, Inputs.VariantTwoArgs>? UnionOf { get; set; }

        public ExampleArgs()
        {
        }
        public static new ExampleArgs Empty => new ExampleArgs();
    }
}
