// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nestedobject
{
    public static class GetValues
    {
        public static Task<GetValuesResult> InvokeAsync(GetValuesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetValuesResult>("nestedobject:index:getValues", args ?? new GetValuesArgs(), options.WithDefaults());

        public static Output<GetValuesResult> Invoke(GetValuesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetValuesResult>("nestedobject:index:getValues", args ?? new GetValuesInvokeArgs(), options.WithDefaults());

        public static Output<GetValuesResult> Invoke(GetValuesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetValuesResult>("nestedobject:index:getValues", args ?? new GetValuesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetValuesArgs : global::Pulumi.InvokeArgs
    {
        [Input("names", required: true)]
        private List<string>? _names;
        public List<string> Names
        {
            get => _names ?? (_names = new List<string>());
            set => _names = value;
        }

        public GetValuesArgs()
        {
        }
        public static new GetValuesArgs Empty => new GetValuesArgs();
    }

    public sealed class GetValuesInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("names", required: true)]
        private InputList<string>? _names;
        public InputList<string> Names
        {
            get => _names ?? (_names = new InputList<string>());
            set => _names = value;
        }

        public GetValuesInvokeArgs()
        {
        }
        public static new GetValuesInvokeArgs Empty => new GetValuesInvokeArgs();
    }


    [OutputType]
    public sealed class GetValuesResult
    {
        public readonly ImmutableArray<string> Results;

        [OutputConstructor]
        private GetValuesResult(ImmutableArray<string> results)
        {
            Results = results;
        }
    }
}
