// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nestedobject
{
    [NestedobjectResourceType("nestedobject:index:MapContainer")]
    public partial class MapContainer : global::Pulumi.CustomResource
    {
        [Output("tags")]
        public Output<ImmutableDictionary<string, string>> Tags { get; private set; } = null!;


        /// <summary>
        /// Create a MapContainer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MapContainer(string name, MapContainerArgs args, CustomResourceOptions? options = null)
            : base("nestedobject:index:MapContainer", name, args ?? new MapContainerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MapContainer(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nestedobject:index:MapContainer", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MapContainer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MapContainer Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new MapContainer(name, id, options);
        }
    }

    public sealed class MapContainerArgs : global::Pulumi.ResourceArgs
    {
        [Input("tags", required: true)]
        private InputMap<string>? _tags;
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        public MapContainerArgs()
        {
        }
        public static new MapContainerArgs Empty => new MapContainerArgs();
    }
}
