// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nestedobject
{
    [NestedobjectResourceType("nestedobject:index:Receiver")]
    public partial class Receiver : global::Pulumi.CustomResource
    {
        [Output("details")]
        public Output<ImmutableArray<Outputs.Detail>> Details { get; private set; } = null!;


        /// <summary>
        /// Create a Receiver resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Receiver(string name, ReceiverArgs args, CustomResourceOptions? options = null)
            : base("nestedobject:index:Receiver", name, args ?? new ReceiverArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Receiver(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nestedobject:index:Receiver", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Receiver resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Receiver Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Receiver(name, id, options);
        }
    }

    public sealed class ReceiverArgs : global::Pulumi.ResourceArgs
    {
        [Input("details", required: true)]
        private InputList<Inputs.DetailArgs>? _details;
        public InputList<Inputs.DetailArgs> Details
        {
            get => _details ?? (_details = new InputList<Inputs.DetailArgs>());
            set => _details = value;
        }

        public ReceiverArgs()
        {
        }
        public static new ReceiverArgs Empty => new ReceiverArgs();
    }
}
