<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <RestoreSources>ROOT/artifacts/Pulumi;ROOT/artifacts/Pulumi.Subpackage;$(RestoreSources)</RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pulumi" />
    <PackageReference Include="Pulumi.Subpackage" />
  </ItemGroup>
</Project>