// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Keywords
{
    [KeywordsResourceType("keywords:index:Lambda")]
    public partial class Lambda : global::Pulumi.CustomResource
    {
        [Output("builtins")]
        public Output<string> Builtins { get; private set; } = null!;

        [Output("lambda")]
        public Output<string> Lambda { get; private set; } = null!;

        [Output("property")]
        public Output<string> Property { get; private set; } = null!;


        /// <summary>
        /// Create a Lambda resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Lambda(string name, LambdaArgs args, CustomResourceOptions? options = null)
            : base("keywords:index:Lambda", name, args ?? new LambdaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Lambda(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("keywords:index:Lambda", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Lambda resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Lambda Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Lambda(name, id, options);
        }
    }

    public sealed class LambdaArgs : global::Pulumi.ResourceArgs
    {
        [Input("builtins", required: true)]
        public Input<string> Builtins { get; set; } = null!;

        [Input("lambda", required: true)]
        public Input<string> Lambda { get; set; } = null!;

        [Input("property", required: true)]
        public Input<string> Property { get; set; } = null!;

        public LambdaArgs()
        {
        }
        public static new LambdaArgs Empty => new LambdaArgs();
    }
}
