// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SimpleInvoke
{
    public static class GetText
    {
        public static Task<GetTextResult> InvokeAsync(GetTextArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTextResult>("simple-invoke:index:getText", args ?? new GetTextArgs(), options.WithDefaults());

        public static Output<GetTextResult> Invoke(GetTextInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTextResult>("simple-invoke:index:getText", args ?? new GetTextInvokeArgs(), options.WithDefaults());

        public static Output<GetTextResult> Invoke(GetTextInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTextResult>("simple-invoke:index:getText", args ?? new GetTextInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTextArgs : global::Pulumi.InvokeArgs
    {
        [Input("text", required: true)]
        public string Text { get; set; } = null!;

        public GetTextArgs()
        {
        }
        public static new GetTextArgs Empty => new GetTextArgs();
    }

    public sealed class GetTextInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("text", required: true)]
        public Input<string> Text { get; set; } = null!;

        public GetTextInvokeArgs()
        {
        }
        public static new GetTextInvokeArgs Empty => new GetTextInvokeArgs();
    }


    [OutputType]
    public sealed class GetTextResult
    {
        public readonly string Result;

        [OutputConstructor]
        private GetTextResult(string result)
        {
            Result = result;
        }
    }
}
