// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.SimpleInvoke
{
    public static class InvokeWithDefault
    {
        public static Task<InvokeWithDefaultResult> InvokeAsync(InvokeWithDefaultArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<InvokeWithDefaultResult>("simple-invoke:index:invokeWithDefault", args ?? new InvokeWithDefaultArgs(), options.WithDefaults());

        public static Output<InvokeWithDefaultResult> Invoke(InvokeWithDefaultInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<InvokeWithDefaultResult>("simple-invoke:index:invokeWithDefault", args ?? new InvokeWithDefaultInvokeArgs(), options.WithDefaults());

        public static Output<InvokeWithDefaultResult> Invoke(InvokeWithDefaultInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<InvokeWithDefaultResult>("simple-invoke:index:invokeWithDefault", args ?? new InvokeWithDefaultInvokeArgs(), options.WithDefaults());
    }


    public sealed class InvokeWithDefaultArgs : global::Pulumi.InvokeArgs
    {
        [Input("value")]
        public string? Value { get; set; }

        public InvokeWithDefaultArgs()
        {
            Value = "default";
        }
        public static new InvokeWithDefaultArgs Empty => new InvokeWithDefaultArgs();
    }

    public sealed class InvokeWithDefaultInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value")]
        public Input<string>? Value { get; set; }

        public InvokeWithDefaultInvokeArgs()
        {
            Value = "default";
        }
        public static new InvokeWithDefaultInvokeArgs Empty => new InvokeWithDefaultInvokeArgs();
    }


    [OutputType]
    public sealed class InvokeWithDefaultResult
    {
        public readonly string Result;

        [OutputConstructor]
        private InvokeWithDefaultResult(string result)
        {
            Result = result;
        }
    }
}
