// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Primitive
{
    public static class InvokeFunction
    {
        public static Task<InvokeFunctionResult> InvokeAsync(InvokeFunctionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<InvokeFunctionResult>("primitive:index:invoke", args ?? new InvokeFunctionArgs(), options.WithDefaults());

        public static Output<InvokeFunctionResult> Invoke(InvokeFunctionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<InvokeFunctionResult>("primitive:index:invoke", args ?? new InvokeFunctionInvokeArgs(), options.WithDefaults());

        public static Output<InvokeFunctionResult> Invoke(InvokeFunctionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<InvokeFunctionResult>("primitive:index:invoke", args ?? new InvokeFunctionInvokeArgs(), options.WithDefaults());
    }


    public sealed class InvokeFunctionArgs : global::Pulumi.InvokeArgs
    {
        [Input("boolean", required: true)]
        public bool Boolean { get; set; }

        [Input("booleanMap", required: true)]
        private Dictionary<string, bool>? _booleanMap;
        public Dictionary<string, bool> BooleanMap
        {
            get => _booleanMap ?? (_booleanMap = new Dictionary<string, bool>());
            set => _booleanMap = value;
        }

        [Input("float", required: true)]
        public double Float { get; set; }

        [Input("integer", required: true)]
        public int Integer { get; set; }

        [Input("numberArray", required: true)]
        private List<double>? _numberArray;
        public List<double> NumberArray
        {
            get => _numberArray ?? (_numberArray = new List<double>());
            set => _numberArray = value;
        }

        [Input("string", required: true)]
        public string String { get; set; } = null!;

        public InvokeFunctionArgs()
        {
        }
        public static new InvokeFunctionArgs Empty => new InvokeFunctionArgs();
    }

    public sealed class InvokeFunctionInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("boolean", required: true)]
        public Input<bool> Boolean { get; set; } = null!;

        [Input("booleanMap", required: true)]
        private InputMap<bool>? _booleanMap;
        public InputMap<bool> BooleanMap
        {
            get => _booleanMap ?? (_booleanMap = new InputMap<bool>());
            set => _booleanMap = value;
        }

        [Input("float", required: true)]
        public Input<double> Float { get; set; } = null!;

        [Input("integer", required: true)]
        public Input<int> Integer { get; set; } = null!;

        [Input("numberArray", required: true)]
        private InputList<double>? _numberArray;
        public InputList<double> NumberArray
        {
            get => _numberArray ?? (_numberArray = new InputList<double>());
            set => _numberArray = value;
        }

        [Input("string", required: true)]
        public Input<string> String { get; set; } = null!;

        public InvokeFunctionInvokeArgs()
        {
        }
        public static new InvokeFunctionInvokeArgs Empty => new InvokeFunctionInvokeArgs();
    }


    [OutputType]
    public sealed class InvokeFunctionResult
    {
        public readonly bool Boolean;
        public readonly ImmutableDictionary<string, bool> BooleanMap;
        public readonly double Float;
        public readonly int Integer;
        public readonly ImmutableArray<double> NumberArray;
        public readonly string String;

        [OutputConstructor]
        private InvokeFunctionResult(
            bool boolean,

            ImmutableDictionary<string, bool> booleanMap,

            double @float,

            int integer,

            ImmutableArray<double> numberArray,

            string @string)
        {
            Boolean = boolean;
            BooleanMap = booleanMap;
            Float = @float;
            Integer = integer;
            NumberArray = numberArray;
            String = @string;
        }
    }
}
