// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Primitive
{
    [PrimitiveResourceType("primitive:index:Resource")]
    public partial class Resource : global::Pulumi.CustomResource
    {
        [Output("boolean")]
        public Output<bool> Boolean { get; private set; } = null!;

        [Output("booleanMap")]
        public Output<ImmutableDictionary<string, bool>> BooleanMap { get; private set; } = null!;

        [Output("float")]
        public Output<double> Float { get; private set; } = null!;

        [Output("integer")]
        public Output<int> Integer { get; private set; } = null!;

        [Output("numberArray")]
        public Output<ImmutableArray<double>> NumberArray { get; private set; } = null!;

        [Output("string")]
        public Output<string> String { get; private set; } = null!;


        /// <summary>
        /// Create a Resource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Resource(string name, ResourceArgs args, CustomResourceOptions? options = null)
            : base("primitive:index:Resource", name, args ?? new ResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Resource(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("primitive:index:Resource", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Resource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Resource Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Resource(name, id, options);
        }
    }

    public sealed class ResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("boolean", required: true)]
        public Input<bool> Boolean { get; set; } = null!;

        [Input("booleanMap", required: true)]
        private InputMap<bool>? _booleanMap;
        public InputMap<bool> BooleanMap
        {
            get => _booleanMap ?? (_booleanMap = new InputMap<bool>());
            set => _booleanMap = value;
        }

        [Input("float", required: true)]
        public Input<double> Float { get; set; } = null!;

        [Input("integer", required: true)]
        public Input<int> Integer { get; set; } = null!;

        [Input("numberArray", required: true)]
        private InputList<double>? _numberArray;
        public InputList<double> NumberArray
        {
            get => _numberArray ?? (_numberArray = new InputList<double>());
            set => _numberArray = value;
        }

        [Input("string", required: true)]
        public Input<string> String { get; set; } = null!;

        public ResourceArgs()
        {
        }
        public static new ResourceArgs Empty => new ResourceArgs();
    }
}
