// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pkg
{
    /// <summary>
    /// A test resource that echoes its input.
    /// </summary>
    [PkgResourceType("pkg:index:Echo")]
    public partial class Echo : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Input to echo.
        /// </summary>
        [Output("value")]
        public Output<object?> Value { get; private set; } = null!;


        /// <summary>
        /// Create a Echo resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Echo(string name, EchoArgs? args = null, CustomResourceOptions? options = null)
            : base("pkg:index:Echo", name, args ?? new EchoArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private Echo(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pkg:index:Echo", name, null, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Echo resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Echo Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Echo(name, id, options);
        }
    }

    public sealed class EchoArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Input to echo.
        /// </summary>
        [Input("value")]
        public Input<object>? Value { get; set; }

        public EchoArgs()
        {
        }
        public static new EchoArgs Empty => new EchoArgs();
    }
}
