// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Call
{
    /// <summary>
    /// The `call` package's provider resource
    /// </summary>
    [CallResourceType("pulumi:providers:call")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("call", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }

        /// <summary>
        /// The `identity` method of the `call` package's provider. Returns the provider's `value` configuration unaltered.
        /// </summary>
        public global::Pulumi.Output<ProviderIdentityResult> Identity()
            => global::Pulumi.Deployment.Instance.Call<ProviderIdentityResult>("pulumi:providers:call/identity", CallArgs.Empty, this);

        /// <summary>
        /// The `prefixed` method of the `call` package's provider. Accepts a string and returns the provider's `value` configuration prefixed with that string.
        /// </summary>
        public global::Pulumi.Output<ProviderPrefixedResult> Prefixed(ProviderPrefixedArgs args)
            => global::Pulumi.Deployment.Instance.Call<ProviderPrefixedResult>("pulumi:providers:call/prefixed", args ?? new ProviderPrefixedArgs(), this);
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }

    /// <summary>
    /// The results of the <see cref="Provider.Identity"/> method.
    /// </summary>
    [OutputType]
    public sealed class ProviderIdentityResult
    {
        public readonly string Result;

        [OutputConstructor]
        private ProviderIdentityResult(string result)
        {
            Result = result;
        }
    }

    /// <summary>
    /// The set of arguments for the <see cref="Provider.Prefixed"/> method.
    /// </summary>
    public sealed class ProviderPrefixedArgs : global::Pulumi.CallArgs
    {
        [Input("prefix", required: true)]
        public Input<string> Prefix { get; set; } = null!;

        public ProviderPrefixedArgs()
        {
        }
        public static new ProviderPrefixedArgs Empty => new ProviderPrefixedArgs();
    }

    /// <summary>
    /// The results of the <see cref="Provider.Prefixed"/> method.
    /// </summary>
    [OutputType]
    public sealed class ProviderPrefixedResult
    {
        public readonly string Result;

        [OutputConstructor]
        private ProviderPrefixedResult(string result)
        {
            Result = result;
        }
    }
}
