// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnion.Inputs
{

    public sealed class VariantOneArgs : global::Pulumi.ResourceArgs
    {
        [Input("discriminantKind", required: true)]
        public Input<string> DiscriminantKind { get; set; } = null!;

        [Input("field1")]
        public Input<string>? Field1 { get; set; }

        public VariantOneArgs()
        {
        }
        public static new VariantOneArgs Empty => new VariantOneArgs();
    }
}
