// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ModuleFormat.Mod.Nested
{
    [ModuleFormatResourceType("module-format:mod/nested_Resource:Resource")]
    public partial class Resource : global::Pulumi.CustomResource
    {
        [Output("text")]
        public Output<string> Text { get; private set; } = null!;


        /// <summary>
        /// Create a Resource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Resource(string name, ResourceArgs args, CustomResourceOptions? options = null)
            : base("module-format:mod/nested_Resource:Resource", name, args ?? new ResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Resource(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("module-format:mod/nested_Resource:Resource", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Resource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Resource Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Resource(name, id, options);
        }

        public global::Pulumi.Output<ResourceCallResult> Call(ResourceCallArgs args)
            => global::Pulumi.Deployment.Instance.Call<ResourceCallResult>("module-format:mod/nested_Resource:Resource/call", args ?? new ResourceCallArgs(), this);
    }

    public sealed class ResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("text", required: true)]
        public Input<string> Text { get; set; } = null!;

        public ResourceArgs()
        {
        }
        public static new ResourceArgs Empty => new ResourceArgs();
    }

    /// <summary>
    /// The set of arguments for the <see cref="Resource.Call"/> method.
    /// </summary>
    public sealed class ResourceCallArgs : global::Pulumi.CallArgs
    {
        [Input("input", required: true)]
        public Input<string> Input { get; set; } = null!;

        public ResourceCallArgs()
        {
        }
        public static new ResourceCallArgs Empty => new ResourceCallArgs();
    }

    /// <summary>
    /// The results of the <see cref="Resource.Call"/> method.
    /// </summary>
    [OutputType]
    public sealed class ResourceCallResult
    {
        public readonly double Output;

        [OutputConstructor]
        private ResourceCallResult(double output)
        {
            Output = output;
        }
    }
}
