<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))"/>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3"/>
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3"/>
    <PackageVersion Include="Pulumi.Aws" Version="7.41.0"/>
    <PackageVersion Include="Pulumi.Random" Version="4.21.1"/>
  </ItemGroup>
</Project>
