// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Goodbye
{
    [GoodbyeResourceType("goodbye:index:Goodbye")]
    public partial class Goodbye : global::Pulumi.CustomResource
    {
        [Output("parameterValue")]
        public Output<string> ParameterValue { get; private set; } = null!;


        /// <summary>
        /// Create a Goodbye resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Goodbye(string name, GoodbyeArgs? args = null, CustomResourceOptions? options = null)
            : base("goodbye:index:Goodbye", name, args ?? new GoodbyeArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private Goodbye(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("goodbye:index:Goodbye", name, null, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Goodbye resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Goodbye Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Goodbye(name, id, options);
        }
    }

    public sealed class GoodbyeArgs : global::Pulumi.ResourceArgs
    {
        public GoodbyeArgs()
        {
        }
        public static new GoodbyeArgs Empty => new GoodbyeArgs();
    }
}
