// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Inputs
{

    public sealed class Variant4Args : global::Pulumi.ResourceArgs
    {
        [Input("discriminantKind", required: true)]
        public Input<string> DiscriminantKind { get; set; } = null!;

        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("payload")]
        public Input<string>? Payload { get; set; }

        public Variant4Args()
        {
            DiscriminantKind = "variant4";
        }
        public static new Variant4Args Empty => new Variant4Args();
    }
}
