// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Inputs
{

    public sealed class Variant8Args : global::Pulumi.ResourceArgs
    {
        [Input("discriminantKind", required: true)]
        public Input<string> DiscriminantKind { get; set; } = null!;

        [Input("payload")]
        public Input<string>? Payload { get; set; }

        [Input("size")]
        public Input<int>? Size { get; set; }

        public Variant8Args()
        {
            DiscriminantKind = "variant8";
        }
        public static new Variant8Args Empty => new Variant8Args();
    }
}
