// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnionMany.Inputs
{

    public sealed class Variant5Args : global::Pulumi.ResourceArgs
    {
        [Input("discriminantKind", required: true)]
        public Input<string> DiscriminantKind { get; set; } = null!;

        [Input("label")]
        public Input<string>? Label { get; set; }

        [Input("payload")]
        public Input<string>? Payload { get; set; }

        public Variant5Args()
        {
        }
        public static new Variant5Args Empty => new Variant5Args();
    }
}
