// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Enum
{
    [EnumResourceType("enum:index:Deluxe")]
    public partial class Deluxe : global::Pulumi.CustomResource
    {
        [Output("arrayOfEnum")]
        public Output<ImmutableArray<Pulumi.Enum.StringEnum>> ArrayOfEnum { get; private set; } = null!;

        [Output("holder")]
        public Output<Outputs.Holder?> Holder { get; private set; } = null!;

        [Output("mapOfEnum")]
        public Output<ImmutableDictionary<string, Pulumi.Enum.IntEnum>?> MapOfEnum { get; private set; } = null!;

        [Output("numberEnum")]
        public Output<Pulumi.Enum.NumberEnum?> NumberEnum { get; private set; } = null!;

        [Output("unionEnum")]
        public Output<string?> UnionEnum { get; private set; } = null!;

        [Output("wordyEnum")]
        public Output<Pulumi.Enum.WordyEnum?> WordyEnum { get; private set; } = null!;


        /// <summary>
        /// Create a Deluxe resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Deluxe(string name, DeluxeArgs? args = null, CustomResourceOptions? options = null)
            : base("enum:index:Deluxe", name, args ?? new DeluxeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Deluxe(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("enum:index:Deluxe", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Deluxe resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Deluxe Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Deluxe(name, id, options);
        }
    }

    public sealed class DeluxeArgs : global::Pulumi.ResourceArgs
    {
        [Input("arrayOfEnum")]
        private InputList<Pulumi.Enum.StringEnum>? _arrayOfEnum;
        public InputList<Pulumi.Enum.StringEnum> ArrayOfEnum
        {
            get => _arrayOfEnum ?? (_arrayOfEnum = new InputList<Pulumi.Enum.StringEnum>());
            set => _arrayOfEnum = value;
        }

        [Input("holder")]
        public Input<Inputs.HolderArgs>? Holder { get; set; }

        [Input("mapOfEnum")]
        private InputMap<Pulumi.Enum.IntEnum>? _mapOfEnum;
        public InputMap<Pulumi.Enum.IntEnum> MapOfEnum
        {
            get => _mapOfEnum ?? (_mapOfEnum = new InputMap<Pulumi.Enum.IntEnum>());
            set => _mapOfEnum = value;
        }

        [Input("numberEnum")]
        public Input<Pulumi.Enum.NumberEnum>? NumberEnum { get; set; }

        [Input("unionEnum")]
        public InputUnion<Pulumi.Enum.WordyEnum, string>? UnionEnum { get; set; }

        [Input("wordyEnum")]
        public Input<Pulumi.Enum.WordyEnum>? WordyEnum { get; set; }

        public DeluxeArgs()
        {
        }
        public static new DeluxeArgs Empty => new DeluxeArgs();
    }
}
