// Copyright 2016-2026, Pulumi Corporation

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Pulumi.Automation.Codegen
{
    /// <summary>
    /// Shared emission helpers for the generated source files: the file
    /// header, XML documentation comments, and the final normalization pass.
    /// </summary>
    internal static class Emitter
    {
        /// <summary>
        /// Normalizes a compilation unit into the repository's house style and
        /// returns its source text: four-space indentation, LF line endings, a
        /// blank line between sibling members, the licence/generated header,
        /// and a trailing newline.
        /// </summary>
        public static string Render(CompilationUnitSyntax unit)
        {
            unit = unit.NormalizeWhitespace(indentation: "    ", eol: "\n");
            unit = SeparateMembersWithBlankLines(unit);
            unit = unit.WithLeadingTrivia(ParseLeadingTrivia(Header()).AddRange(unit.GetLeadingTrivia()));

            // End the file with a newline, per the repository's convention for
            // .cs files.
            unit = unit.WithEndOfFileToken(unit.EndOfFileToken.WithLeadingTrivia(LineFeed));

            return unit.ToFullString();
        }

        /// <summary>
        /// Builds the leading trivia for an XML <c>&lt;summary&gt;</c>
        /// documentation comment. Comments are trivia rather than nodes in
        /// Roslyn, so the text is assembled (escaping documentation content
        /// when requested) and parsed into structured trivia.
        /// </summary>
        public static SyntaxTriviaList SummaryComment(IEnumerable<string> lines, bool escape)
        {
            var builder = new StringBuilder();
            builder.Append("/// <summary>\n");
            foreach (var line in lines)
            {
                var text = escape ? EscapeXml(line) : line;
                builder.Append($"/// {text.TrimEnd()}".TrimEnd()).Append('\n');
            }

            builder.Append("/// </summary>\n");
            return ParseLeadingTrivia(builder.ToString());
        }

        /// <summary>
        /// Builds the leading trivia for a single-line XML
        /// <c>&lt;summary&gt;</c> comment.
        /// </summary>
        public static SyntaxTriviaList SummaryComment(string line)
            => SummaryComment(new[] { line }, escape: false);

        /// <summary>
        /// Escapes the characters that would otherwise be interpreted as XML
        /// markup inside a documentation comment.
        /// </summary>
        public static string EscapeXml(string value)
            => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

        private static string Header()
            => $"// Copyright {DateTime.Now.Year.ToString(CultureInfo.InvariantCulture)}, Pulumi Corporation\n" +
               "\n" +
               "// <auto-generated>\n" +
               "//     Code generated by Pulumi.Automation.Codegen. DO NOT EDIT.\n" +
               "// </auto-generated>\n" +
               "\n" +
               "#nullable enable\n" +
               "\n";

        /// <summary>
        /// Inserts a blank line before every property declaration other than
        /// the first member of its class. NormalizeWhitespace already
        /// separates methods (and type declarations) with a blank line but
        /// packs properties together.
        /// </summary>
        private static CompilationUnitSyntax SeparateMembersWithBlankLines(CompilationUnitSyntax unit)
        {
            var followers = unit.DescendantNodes()
                .OfType<PropertyDeclarationSyntax>()
                .Where(property => property.Parent is ClassDeclarationSyntax parent && parent.Members[0] != property);

            return unit.ReplaceNodes(
                followers,
                (_, property) => property.WithLeadingTrivia(property.GetLeadingTrivia().Insert(0, LineFeed)));
        }
    }
}
