// Copyright 2016-2026, Pulumi Corporation

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Pulumi.Automation.Codegen
{
    /// <summary>
    /// Generates one options class per executable CLI command from a CLI
    /// specification.
    /// </summary>
    /// <remarks>
    /// Flags are flattened: each command's options type contains the flags
    /// declared on the command itself plus those inherited from its ancestors,
    /// with the closest declaration winning when names collide. Override
    /// information (omit and preset) applies only at the node that declares
    /// it and is stripped during descent; flags that remain omitted are not
    /// exposed as properties.
    /// </remarks>
    public static class OptionsGenerator
    {
        private const string Header =
            "// Copyright 2016-2026, Pulumi Corporation\n" +
            "\n" +
            "// <auto-generated>\n" +
            "//     Code generated by Pulumi.Automation.Codegen. DO NOT EDIT.\n" +
            "// </auto-generated>\n" +
            "\n" +
            "#nullable enable\n" +
            "\n";

        /// <summary>
        /// Generates the options classes for every executable command in the
        /// given CLI specification, as a single C# source file.
        /// </summary>
        public static string Generate(CommandTreeNode root, string namespaceName)
        {
            var classes = new List<OptionsClass>();
            Collect(root, new List<string>(), new Dictionary<string, Flag>(StringComparer.Ordinal), classes);

            var byName = new Dictionary<string, OptionsClass>(StringComparer.Ordinal);
            foreach (var optionsClass in classes)
            {
                if (byName.TryGetValue(optionsClass.Name, out var existing))
                {
                    throw new InvalidOperationException(
                        $"The commands `{existing.CliCommand}` and `{optionsClass.CliCommand}` both produce " +
                        $"an options class named {optionsClass.Name}.");
                }

                byName.Add(optionsClass.Name, optionsClass);
            }

            return Emit(classes, namespaceName);
        }

        private sealed record OptionsClass(string Name, string CliCommand, List<Flag> VisibleFlags);

        private static void Collect(
            CommandTreeNode node,
            List<string> breadcrumbs,
            Dictionary<string, Flag> inherited,
            List<OptionsClass> classes)
        {
            // Merge inherited flags with this node's local flags. The local
            // (deeper) declaration wins, which lets a command redefine a flag
            // it inherits with a different type.
            var all = new Dictionary<string, Flag>(inherited, StringComparer.Ordinal);
            foreach (var (name, flag) in node.Flags ?? new Dictionary<string, Flag>())
            {
                all[name] = flag;
            }

            var executable = true;
            if (node is MenuNode menu)
            {
                executable = menu.Executable;
            }

            if (executable)
            {
                if (breadcrumbs.Count == 0)
                {
                    throw new InvalidOperationException("The root of the CLI specification must not be executable.");
                }

                var visibleFlags = all.Values
                    .Where(flag => !flag.Omit)
                    .OrderBy(flag => flag.Name, StringComparer.Ordinal)
                    .ToList();

                var className = "Pulumi" + Names.PascalCase(breadcrumbs) + "Options";
                classes.Add(new OptionsClass(className, "pulumi " + string.Join(" ", breadcrumbs), visibleFlags));
            }

            if (node is MenuNode menuWithChildren && menuWithChildren.Commands != null)
            {
                var childInherited = all.ToDictionary(
                    pair => pair.Key,
                    pair => pair.Value.WithoutOverrides(),
                    StringComparer.Ordinal);

                foreach (var (name, child) in menuWithChildren.Commands.OrderBy(pair => pair.Key, StringComparer.Ordinal))
                {
                    Collect(child, breadcrumbs.Append(name).ToList(), childInherited, classes);
                }
            }
        }

        private static string Emit(List<OptionsClass> classes, string namespaceName)
        {
            var namespaceDeclaration = NamespaceDeclaration(ParseName(namespaceName))
                .WithMembers(List<MemberDeclarationSyntax>(classes.Select(EmitClass)));

            var unit = CompilationUnit()
                .WithMembers(SingletonList<MemberDeclarationSyntax>(namespaceDeclaration));

            if (classes.Any(optionsClass => optionsClass.VisibleFlags.Any(flag => flag.Repeatable)))
            {
                unit = unit.WithUsings(SingletonList(UsingDirective(ParseName("System.Collections.Generic"))));
            }

            unit = unit.NormalizeWhitespace(indentation: "    ", eol: "\n");
            unit = SeparatePropertiesWithBlankLines(unit);
            unit = unit.WithLeadingTrivia(ParseLeadingTrivia(Header).AddRange(unit.GetLeadingTrivia()));

            // End the file with a newline, per the repository's convention
            // for .cs files.
            unit = unit.WithEndOfFileToken(unit.EndOfFileToken.WithLeadingTrivia(LineFeed));

            return unit.ToFullString();
        }

        private static ClassDeclarationSyntax EmitClass(OptionsClass optionsClass)
        {
            var properties = new List<MemberDeclarationSyntax>();
            var propertyNames = new Dictionary<string, string>(StringComparer.Ordinal);

            foreach (var flag in optionsClass.VisibleFlags)
            {
                var propertyName = Names.PascalCase(flag.Name);

                if (propertyName == optionsClass.Name)
                {
                    throw new InvalidOperationException(
                        $"The flag --{flag.Name} of `{optionsClass.CliCommand}` produces a property named like " +
                        $"its containing class ({propertyName}).");
                }

                if (propertyNames.TryGetValue(propertyName, out var existing))
                {
                    throw new InvalidOperationException(
                        $"The flags --{existing} and --{flag.Name} of `{optionsClass.CliCommand}` both produce " +
                        $"a property named {propertyName}.");
                }

                propertyNames.Add(propertyName, flag.Name);

                var property = PropertyDeclaration(ParseTypeName(PropertyType(flag)), Identifier(propertyName))
                    .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword)))
                    .WithAccessorList(AccessorList(List(new[]
                    {
                        AccessorDeclaration(SyntaxKind.GetAccessorDeclaration)
                            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                        AccessorDeclaration(SyntaxKind.SetAccessorDeclaration)
                            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken)),
                    })));

                if (!string.IsNullOrEmpty(flag.Description))
                {
                    property = property.WithLeadingTrivia(DocComment(flag.Description.Split('\n'), escape: true));
                }

                properties.Add(property);
            }

            return ClassDeclaration(optionsClass.Name)
                .WithModifiers(TokenList(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.SealedKeyword)))
                .WithMembers(List(properties))
                .WithLeadingTrivia(DocComment(
                    new[] { $"Options for the <c>{optionsClass.CliCommand}</c> command." }, escape: false));
        }

        private static string PropertyType(Flag flag)
        {
            var baseType = flag.Type switch
            {
                "string" => "string",
                "boolean" => "bool",
                "int" => "int",
                _ => throw new InvalidOperationException($"Unknown flag type: \"{flag.Type}\" (flag --{flag.Name})."),
            };

            return flag.Repeatable ? $"List<{baseType}>?" : $"{baseType}?";
        }

        /// <summary>
        /// Builds the leading trivia for an XML documentation comment.
        /// Comments are trivia rather than nodes in Roslyn, so the text is
        /// assembled (escaping documentation content as needed) and parsed
        /// into structured trivia.
        /// </summary>
        private static SyntaxTriviaList DocComment(IEnumerable<string> lines, bool escape)
        {
            var builder = new StringBuilder();
            builder.Append("/// <summary>\n");
            foreach (var line in lines)
            {
                var text = escape ? EscapeXml(line) : line;
                builder.Append($"/// {text.TrimEnd()}".TrimEnd()).Append('\n');
            }

            builder.Append("/// </summary>\n");
            return ParseLeadingTrivia(builder.ToString());
        }

        /// <summary>
        /// Inserts a blank line before every property declaration other than
        /// the first member of its class. NormalizeWhitespace separates type
        /// declarations with a blank line but packs properties together.
        /// </summary>
        private static CompilationUnitSyntax SeparatePropertiesWithBlankLines(CompilationUnitSyntax unit)
        {
            var followers = unit.DescendantNodes()
                .OfType<PropertyDeclarationSyntax>()
                .Where(property => property.Parent is ClassDeclarationSyntax parent && parent.Members[0] != property);

            return unit.ReplaceNodes(
                followers,
                (_, property) => property.WithLeadingTrivia(property.GetLeadingTrivia().Insert(0, LineFeed)));
        }

        private static string EscapeXml(string value)
            => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
