// Copyright 2026, Pulumi Corporation

// <auto-generated>
//     Code generated by Pulumi.Automation.Codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Threading.Tasks;

namespace Pulumi.Automation.Commands
{
    /// <summary>
    /// Runs Pulumi CLI commands, one method per command. The invocation itself is provided by the boilerplate half of this partial class.
    /// </summary>
    public sealed partial class API
    {
        /// <summary>
        /// Runs the <c>pulumi cancel</c> command.
        /// </summary>
        public Task<CommandResult> CancelAsync(string? stackName = null, PulumiCancelOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "cancel"
            };
            __final.Add("--yes");
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Stack is { } __valueStack)
            {
                __final.Add("--stack");
                __final.Add(__valueStack);
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            var __arguments = new List<string>();
            if (stackName != null)
            {
                __arguments.Add(stackName);
            }

            if (__arguments.Count > 0)
            {
                __final.Add("--");
                __final.AddRange(__arguments);
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi import</c> command.
        /// </summary>
        public Task<CommandResult> ImportAsync(IEnumerable<string>? arg = null, PulumiImportOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "import"
            };
            __final.Add("--skip-preview");
            __final.Add("--yes");
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.ConfigFile is { } __valueConfigFile)
            {
                __final.Add("--config-file");
                __final.Add(__valueConfigFile);
            }

            if (options?.Debug is true)
            {
                __final.Add("--debug");
            }

            if (options?.Diff is true)
            {
                __final.Add("--diff");
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.ExecAgent is { } __valueExecAgent)
            {
                __final.Add("--exec-agent");
                __final.Add(__valueExecAgent);
            }

            if (options?.ExecKind is { } __valueExecKind)
            {
                __final.Add("--exec-kind");
                __final.Add(__valueExecKind);
            }

            if (options?.File is { } __valueFile)
            {
                __final.Add("--file");
                __final.Add(__valueFile);
            }

            if (options?.From is { } __valueFrom)
            {
                __final.Add("--from");
                __final.Add(__valueFrom);
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.GenerateCode is true)
            {
                __final.Add("--generate-code");
            }

            if (options?.GenerateResources is { } __valueGenerateResources)
            {
                __final.Add("--generate-resources");
                __final.Add(__valueGenerateResources);
            }

            if (options?.Json is true)
            {
                __final.Add("--json");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Message is { } __valueMessage)
            {
                __final.Add("--message");
                __final.Add(__valueMessage);
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Out is { } __valueOut)
            {
                __final.Add("--out");
                __final.Add(__valueOut);
            }

            if (options?.Output is { } __valueOutput)
            {
                __final.Add("--output");
                __final.Add(__valueOutput);
            }

            if (options?.Parallel is { } __valueParallel)
            {
                __final.Add("--parallel");
                __final.Add(__valueParallel.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Parent is { } __valueParent)
            {
                __final.Add("--parent");
                __final.Add(__valueParent);
            }

            if (options?.PreviewOnly is true)
            {
                __final.Add("--preview-only");
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Properties is { } __valueProperties)
            {
                foreach (var __item in __valueProperties)
                {
                    __final.Add("--properties");
                    __final.Add(__item);
                }
            }

            if (options?.Protect is true)
            {
                __final.Add("--protect");
            }

            if (options?.Provider is { } __valueProvider)
            {
                __final.Add("--provider");
                __final.Add(__valueProvider);
            }

            if (options?.SkipPluginPreInstall is true)
            {
                __final.Add("--skip-plugin-pre-install");
            }

            if (options?.Stack is { } __valueStack)
            {
                __final.Add("--stack");
                __final.Add(__valueStack);
            }

            if (options?.SuppressOutputs is true)
            {
                __final.Add("--suppress-outputs");
            }

            if (options?.SuppressPermalink is { } __valueSuppressPermalink)
            {
                __final.Add("--suppress-permalink");
                __final.Add(__valueSuppressPermalink);
            }

            if (options?.SuppressProgress is true)
            {
                __final.Add("--suppress-progress");
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Urns is true)
            {
                __final.Add("--urns");
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            var __arguments = new List<string>();
            if (arg != null)
            {
                foreach (var __item in arg)
                {
                    __arguments.Add(__item);
                }
            }

            if (__arguments.Count > 0)
            {
                __final.Add("--");
                __final.AddRange(__arguments);
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi new</c> command.
        /// </summary>
        public Task<CommandResult> NewAsync(string? templateOrUrl = null, PulumiNewOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "new"
            };
            __final.Add("--yes");
            if (options?.AI is { } __valueAI)
            {
                __final.Add("--ai");
                __final.Add(__valueAI);
            }

            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.Config is { } __valueConfig)
            {
                foreach (var __item in __valueConfig)
                {
                    __final.Add("--config");
                    __final.Add(__item);
                }
            }

            if (options?.ConfigPath is true)
            {
                __final.Add("--config-path");
            }

            if (options?.Description is { } __valueDescription)
            {
                __final.Add("--description");
                __final.Add(__valueDescription);
            }

            if (options?.Dir is { } __valueDir)
            {
                __final.Add("--dir");
                __final.Add(__valueDir);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.Force is true)
            {
                __final.Add("--force");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.GenerateOnly is true)
            {
                __final.Add("--generate-only");
            }

            if (options?.Language is { } __valueLanguage)
            {
                __final.Add("--language");
                __final.Add(__valueLanguage);
            }

            if (options?.ListTemplates is true)
            {
                __final.Add("--list-templates");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Name is { } __valueName)
            {
                __final.Add("--name");
                __final.Add(__valueName);
            }

            if (options?.Offline is true)
            {
                __final.Add("--offline");
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.RemoteStackConfig is true)
            {
                __final.Add("--remote-stack-config");
            }

            if (options?.RuntimeOptions is { } __valueRuntimeOptions)
            {
                foreach (var __item in __valueRuntimeOptions)
                {
                    __final.Add("--runtime-options");
                    __final.Add(__item);
                }
            }

            if (options?.SecretsProvider is { } __valueSecretsProvider)
            {
                __final.Add("--secrets-provider");
                __final.Add(__valueSecretsProvider);
            }

            if (options?.Stack is { } __valueStack)
            {
                __final.Add("--stack");
                __final.Add(__valueStack);
            }

            if (options?.TemplateMode is true)
            {
                __final.Add("--template-mode");
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            var __arguments = new List<string>();
            if (templateOrUrl != null)
            {
                __arguments.Add(templateOrUrl);
            }

            if (__arguments.Count > 0)
            {
                __final.Add("--");
                __final.AddRange(__arguments);
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi org</c> command.
        /// </summary>
        public Task<CommandResult> OrgAsync(PulumiOrgOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "org"
            };
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi org get-default</c> command.
        /// </summary>
        public Task<CommandResult> OrgGetDefaultAsync(PulumiOrgGetDefaultOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "org",
                "get-default"
            };
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi org search</c> command.
        /// </summary>
        public Task<CommandResult> OrgSearchAsync(PulumiOrgSearchOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "org",
                "search"
            };
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.Delimiter is { } __valueDelimiter)
            {
                __final.Add("--delimiter");
                __final.Add(__valueDelimiter);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Org is { } __valueOrg)
            {
                __final.Add("--org");
                __final.Add(__valueOrg);
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Output is { } __valueOutput)
            {
                __final.Add("--output");
                __final.Add(__valueOutput);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Query is { } __valueQuery)
            {
                foreach (var __item in __valueQuery)
                {
                    __final.Add("--query");
                    __final.Add(__item);
                }
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Web is true)
            {
                __final.Add("--web");
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi org search ai</c> command.
        /// </summary>
        public Task<CommandResult> OrgSearchAIAsync(PulumiOrgSearchAIOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "org",
                "search",
                "ai"
            };
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.Delimiter is { } __valueDelimiter)
            {
                __final.Add("--delimiter");
                __final.Add(__valueDelimiter);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Org is { } __valueOrg)
            {
                __final.Add("--org");
                __final.Add(__valueOrg);
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Output is { } __valueOutput)
            {
                __final.Add("--output");
                __final.Add(__valueOutput);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Query is { } __valueQuery)
            {
                __final.Add("--query");
                __final.Add(__valueQuery);
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.Web is true)
            {
                __final.Add("--web");
            }

            return RunAsync(__final, options, cancellationToken);
        }

        /// <summary>
        /// Runs the <c>pulumi org set-default</c> command.
        /// </summary>
        public Task<CommandResult> OrgSetDefaultAsync(string name, PulumiOrgSetDefaultOptions? options = null, CancellationToken cancellationToken = default)
        {
            var __final = new List<string>
            {
                "org",
                "set-default"
            };
            if (options?.Color is { } __valueColor)
            {
                __final.Add("--color");
                __final.Add(__valueColor);
            }

            if (options?.DisableIntegrityChecking is true)
            {
                __final.Add("--disable-integrity-checking");
            }

            if (options?.FullyQualifyStackNames is true)
            {
                __final.Add("--fully-qualify-stack-names");
            }

            if (options?.Logflow is true)
            {
                __final.Add("--logflow");
            }

            if (options?.Logtostderr is true)
            {
                __final.Add("--logtostderr");
            }

            if (options?.Memprofilerate is { } __valueMemprofilerate)
            {
                __final.Add("--memprofilerate");
                __final.Add(__valueMemprofilerate.ToString(CultureInfo.InvariantCulture));
            }

            if (options?.OtelTraces is { } __valueOtelTraces)
            {
                __final.Add("--otel-traces");
                __final.Add(__valueOtelTraces);
            }

            if (options?.Profiling is { } __valueProfiling)
            {
                __final.Add("--profiling");
                __final.Add(__valueProfiling);
            }

            if (options?.Tracing is { } __valueTracing)
            {
                __final.Add("--tracing");
                __final.Add(__valueTracing);
            }

            if (options?.TracingHeader is { } __valueTracingHeader)
            {
                __final.Add("--tracing-header");
                __final.Add(__valueTracingHeader);
            }

            if (options?.Verbose is { } __valueVerbose)
            {
                __final.Add("--verbose");
                __final.Add(__valueVerbose.ToString(CultureInfo.InvariantCulture));
            }

            var __arguments = new List<string>();
            __arguments.Add(name);
            if (__arguments.Count > 0)
            {
                __final.Add("--");
                __final.AddRange(__arguments);
            }

            return RunAsync(__final, options, cancellationToken);
        }
    }
}
