// Copyright 2026, Pulumi Corporation

// <auto-generated>
//     Code generated by Pulumi.Automation.Codegen. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace Pulumi.Automation.Commands
{
    /// <summary>
    /// Options for the <c>pulumi cancel</c> command.
    /// </summary>
    public sealed class PulumiCancelOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// The name of the stack to operate on. Defaults to the current stack
        /// </summary>
        public string? Stack { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi import</c> command.
    /// </summary>
    public sealed class PulumiImportOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Use the configuration values in the specified file rather than detecting the file name
        /// </summary>
        public string? ConfigFile { get; set; }

        /// <summary>
        /// Print detailed debugging output during resource operations
        /// </summary>
        public bool? Debug { get; set; }

        /// <summary>
        /// Display operation as a rich diff showing the overall change
        /// </summary>
        public bool? Diff { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        public string? ExecAgent { get; set; }

        public string? ExecKind { get; set; }

        /// <summary>
        /// The path to a JSON-encoded file containing a list of resources to import
        /// </summary>
        public string? File { get; set; }

        /// <summary>
        /// Invoke a converter to import the resources
        /// </summary>
        public string? From { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Generate resource declaration code for the imported resources
        /// </summary>
        public bool? GenerateCode { get; set; }

        /// <summary>
        /// When used with --from, always write a JSON-encoded file containing a list of importable resources discovered by conversion to the specified path
        /// </summary>
        public string? GenerateResources { get; set; }

        /// <summary>
        /// Serialize the import diffs, operations, and overall output as JSON
        /// </summary>
        public bool? Json { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Optional message to associate with the update operation
        /// </summary>
        public string? Message { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// The path to the file that will contain the generated resource declarations
        /// </summary>
        public string? Out { get; set; }

        /// <summary>
        /// Output format. Supported values are: default, json
        /// </summary>
        public string? Output { get; set; }

        /// <summary>
        /// Allow P resource operations to run in parallel at once (1 for no parallelism).
        /// </summary>
        public int? Parallel { get; set; }

        /// <summary>
        /// The name and URN of the parent resource in the format name=urn, where name is the variable name of the parent resource
        /// </summary>
        public string? Parent { get; set; }

        /// <summary>
        /// Only show a preview of the import, but don't perform the import itself
        /// </summary>
        public bool? PreviewOnly { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// The property names to use for the import in the format name1,name2
        /// </summary>
        public List<string>? Properties { get; set; }

        /// <summary>
        /// Allow resources to be imported with protection from deletion enabled
        /// </summary>
        public bool? Protect { get; set; }

        /// <summary>
        /// The name and URN of the provider to use for the import in the format name=urn, where name is the variable name for the provider resource
        /// </summary>
        public string? Provider { get; set; }

        /// <summary>
        /// Skip the up-front provider plugin install step; missing plugins are installed lazily by the engine
        /// </summary>
        public bool? SkipPluginPreInstall { get; set; }

        /// <summary>
        /// The name of the stack to operate on. Defaults to the current stack
        /// </summary>
        public string? Stack { get; set; }

        /// <summary>
        /// Suppress display of stack outputs (in case they contain sensitive values)
        /// </summary>
        public bool? SuppressOutputs { get; set; }

        /// <summary>
        /// Suppress display of the state permalink
        /// </summary>
        public string? SuppressPermalink { get; set; }

        /// <summary>
        /// Suppress display of periodic progress dots
        /// </summary>
        public bool? SuppressProgress { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Display full URNs instead of short resource names
        /// </summary>
        public bool? Urns { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi new</c> command.
    /// </summary>
    public sealed class PulumiNewOptions : BaseOptions
    {
        /// <summary>
        /// Prompt to use for Pulumi AI
        /// </summary>
        public string? AI { get; set; }

        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Config to save
        /// </summary>
        public List<string>? Config { get; set; }

        /// <summary>
        /// Config keys contain a path to a property in a map or list to set
        /// </summary>
        public bool? ConfigPath { get; set; }

        /// <summary>
        /// The project description; if not specified, a prompt will request it
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// The location to place the generated project; if not specified, the current directory is used
        /// </summary>
        public string? Dir { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Forces content to be generated even if it would change existing files
        /// </summary>
        public bool? Force { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Generate the project only; do not create a stack, save config, or install dependencies
        /// </summary>
        public bool? GenerateOnly { get; set; }

        /// <summary>
        /// Language to use for Pulumi AI (must be one of TypeScript, JavaScript, Python, Go, C#, Java, or YAML)
        /// </summary>
        public string? Language { get; set; }

        /// <summary>
        /// List locally installed templates and exit
        /// </summary>
        public bool? ListTemplates { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// The project name; if not specified, a prompt will request it
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Use locally cached templates without making any network requests
        /// </summary>
        public bool? Offline { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// Store stack configuration remotely
        /// </summary>
        public bool? RemoteStackConfig { get; set; }

        /// <summary>
        /// Additional options for the language runtime (format: key1=value1,key2=value2)
        /// </summary>
        public List<string>? RuntimeOptions { get; set; }

        /// <summary>
        /// The type of the provider that should be used to encrypt and decrypt secrets (possible choices: default, passphrase, awskms, azurekeyvault, gcpkms, hashivault)
        /// </summary>
        public string? SecretsProvider { get; set; }

        /// <summary>
        /// The stack name; either an existing stack or stack to create; if not specified, a prompt will request it
        /// </summary>
        public string? Stack { get; set; }

        /// <summary>
        /// Run in template mode, which will skip prompting for AI or Template functionality
        /// </summary>
        public bool? TemplateMode { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi org</c> command.
    /// </summary>
    public sealed class PulumiOrgOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi org get-default</c> command.
    /// </summary>
    public sealed class PulumiOrgGetDefaultOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi org search</c> command.
    /// </summary>
    public sealed class PulumiOrgSearchOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Delimiter to use when rendering CSV output.
        /// </summary>
        public string? Delimiter { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Name of the organization to search. Defaults to the current user's default organization.
        /// </summary>
        public string? Org { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Output format. Supported values are: default, json, yaml and csv
        /// </summary>
        public string? Output { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// A Pulumi Query to send to Pulumi Cloud for resource search.May be formatted as a single query, or multiple:
        /// 	-q "type:aws:s3/bucketv2:BucketV2 modified:&gt;=2023-09-01"
        /// 	-q "type:aws:s3/bucketv2:BucketV2" -q "modified:&gt;=2023-09-01"
        /// See https://www.pulumi.com/docs/pulumi-cloud/insights/search/#query-syntax for syntax reference.
        /// </summary>
        public List<string>? Query { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }

        /// <summary>
        /// Open the search results in a web browser.
        /// </summary>
        public bool? Web { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi org search ai</c> command.
    /// </summary>
    public sealed class PulumiOrgSearchAIOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Delimiter to use when rendering CSV output.
        /// </summary>
        public string? Delimiter { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Organization name to search within
        /// </summary>
        public string? Org { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Output format. Supported values are: default, json, yaml and csv
        /// </summary>
        public string? Output { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// Plaintext natural language query
        /// </summary>
        public string? Query { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }

        /// <summary>
        /// Open the search results in a web browser.
        /// </summary>
        public bool? Web { get; set; }
    }

    /// <summary>
    /// Options for the <c>pulumi org set-default</c> command.
    /// </summary>
    public sealed class PulumiOrgSetDefaultOptions : BaseOptions
    {
        /// <summary>
        /// Colorize output. Choices are: always, never, raw, auto
        /// </summary>
        public string? Color { get; set; }

        /// <summary>
        /// Disable integrity checking of checkpoint files
        /// </summary>
        public bool? DisableIntegrityChecking { get; set; }

        /// <summary>
        /// Show fully-qualified stack names
        /// </summary>
        public bool? FullyQualifyStackNames { get; set; }

        /// <summary>
        /// Flow log settings to child processes (like plugins)
        /// </summary>
        public bool? Logflow { get; set; }

        /// <summary>
        /// Log to stderr instead of to files
        /// </summary>
        public bool? Logtostderr { get; set; }

        /// <summary>
        /// Enable more precise (and expensive) memory allocation profiles by setting runtime.MemProfileRate
        /// </summary>
        public int? Memprofilerate { get; set; }

        /// <summary>
        /// Export OpenTelemetry traces to the specified endpoint. Use file:// for local JSON files, grpc:// for remote collectors
        /// </summary>
        public string? OtelTraces { get; set; }

        /// <summary>
        /// Emit CPU and memory profiles and an execution trace to '[filename].[pid].{cpu,mem,trace}', respectively
        /// </summary>
        public string? Profiling { get; set; }

        /// <summary>
        /// Emit tracing to the specified endpoint. Use the `file:` scheme to write tracing data to a local file
        /// </summary>
        public string? Tracing { get; set; }

        /// <summary>
        /// Include the tracing header with the given contents.
        /// </summary>
        public string? TracingHeader { get; set; }

        /// <summary>
        /// Enable verbose logging (e.g., v=3); anything &gt;3 is very verbose
        /// </summary>
        public int? Verbose { get; set; }
    }
}
