<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<PropertyGroup>
		<RestoreSources>ROOT/artifacts/Pulumi;ROOT/artifacts/Pulumi.Borrowbase;ROOT/artifacts/Pulumi.Myborrow;$(RestoreSources)</RestoreSources>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Pulumi.Borrowbase" Version="56.0.0" />
		<PackageReference Include="Pulumi.Myborrow" Version="3.0.0" />
		<PackageReference Include="Pulumi" Version="1.0.0" />
	</ItemGroup>

</Project>