// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Extenumref
{
    [ExtenumrefResourceType("extenumref:index:Sink")]
    public partial class Sink : global::Pulumi.CustomResource
    {
        [Output("stringEnum")]
        public Output<Pulumi.Enum.StringEnum?> StringEnum { get; private set; } = null!;


        /// <summary>
        /// Create a Sink resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Sink(string name, SinkArgs? args = null, CustomResourceOptions? options = null)
            : base("extenumref:index:Sink", name, args ?? new SinkArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Sink(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("extenumref:index:Sink", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Sink resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Sink Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Sink(name, id, options);
        }
    }

    public sealed class SinkArgs : global::Pulumi.ResourceArgs
    {
        [Input("stringEnum")]
        public Input<Pulumi.Enum.StringEnum>? StringEnum { get; set; }

        public SinkArgs()
        {
        }
        public static new SinkArgs Empty => new SinkArgs();
    }
}
