// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.KebabNames.KebabModule.Inputs
{

    public sealed class NestedInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("nestedValue", required: true)]
        public Input<string> NestedValue { get; set; } = null!;

        public NestedInputArgs()
        {
        }
        public static new NestedInputArgs Empty => new NestedInputArgs();
    }
}
