// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Replaceonchanges
{
    [ReplaceonchangesResourceType("replaceonchanges:index:ResourceA")]
    public partial class ResourceA : global::Pulumi.CustomResource
    {
        [Output("replaceProp")]
        public Output<bool?> ReplaceProp { get; private set; } = null!;

        [Output("value")]
        public Output<bool> Value { get; private set; } = null!;


        /// <summary>
        /// Create a ResourceA resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ResourceA(string name, ResourceAArgs args, CustomResourceOptions? options = null)
            : base("replaceonchanges:index:ResourceA", name, args ?? new ResourceAArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ResourceA(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("replaceonchanges:index:ResourceA", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                ReplaceOnChanges =
                {
                    "replaceProp",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ResourceA resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ResourceA Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ResourceA(name, id, options);
        }
    }

    public sealed class ResourceAArgs : global::Pulumi.ResourceArgs
    {
        [Input("replaceProp")]
        public Input<bool>? ReplaceProp { get; set; }

        [Input("value", required: true)]
        public Input<bool> Value { get; set; } = null!;

        public ResourceAArgs()
        {
        }
        public static new ResourceAArgs Empty => new ResourceAArgs();
    }
}
