// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.MultiArgumentInvoke
{
    public static class MultiArgumentInvoke
    {
        public static async Task<MultiArgumentInvokeResult> InvokeAsync(string first, string? second = null, InvokeOptions? invokeOptions = null)
        {
            var builder = ImmutableDictionary.CreateBuilder<string, object?>();
            builder["first"] = first;
            builder["second"] = second;
            var args = new global::Pulumi.DictionaryInvokeArgs(builder.ToImmutableDictionary());
            return await global::Pulumi.Deployment.Instance.InvokeAsync<MultiArgumentInvokeResult>("multi-argument-invoke:index:multiArgumentInvoke", args, invokeOptions.WithDefaults());
        }

        public static Output<MultiArgumentInvokeResult> Invoke(Input<string> first, Input<string?>? second = null, InvokeOptions? invokeOptions = null)
        {
            var builder = ImmutableDictionary.CreateBuilder<string, object?>();
            builder["first"] = first;
            builder["second"] = second;
            var args = new global::Pulumi.DictionaryInvokeArgs(builder.ToImmutableDictionary());
            return global::Pulumi.Deployment.Instance.Invoke<MultiArgumentInvokeResult>("multi-argument-invoke:index:multiArgumentInvoke", args, invokeOptions.WithDefaults());
        }
    }


    [OutputType]
    public sealed class MultiArgumentInvokeResult
    {
        public readonly string Result;

        [OutputConstructor]
        private MultiArgumentInvokeResult(string result)
        {
            Result = result;
        }
    }
}
