<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))"/>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Glob" Version="1.1.9"/>
    <PackageVersion Include="NUnit" Version="4.6.1"/>
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0"/>
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.10"/>
    <PackageVersion Include="ThirdParty.Other" Version="0.1.0"/>
  </ItemGroup>
</Project>
