// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Enum.Inputs
{

    public sealed class HolderArgs : global::Pulumi.ResourceArgs
    {
        [Input("color")]
        public Input<Pulumi.Enum.StringEnum>? Color { get; set; }

        [Input("size")]
        public Input<Pulumi.Enum.IntEnum>? Size { get; set; }

        public HolderArgs()
        {
        }
        public static new HolderArgs Empty => new HolderArgs();
    }
}
