// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalarReturns
{
    public static class InvokeSecret
    {
        public static Task<double> InvokeAsync(InvokeSecretArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingleAsync<double>("scalar-returns:index:invokeSecret", args ?? new InvokeSecretArgs(), options.WithDefaults());

        public static Output<double> Invoke(InvokeSecretInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingle<double>("scalar-returns:index:invokeSecret", args ?? new InvokeSecretInvokeArgs(), options.WithDefaults());

        public static Output<double> Invoke(InvokeSecretInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.InvokeSingle<double>("scalar-returns:index:invokeSecret", args ?? new InvokeSecretInvokeArgs(), options.WithDefaults());
    }


    public sealed class InvokeSecretArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public InvokeSecretArgs()
        {
        }
        public static new InvokeSecretArgs Empty => new InvokeSecretArgs();
    }

    public sealed class InvokeSecretInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public InvokeSecretInvokeArgs()
        {
        }
        public static new InvokeSecretInvokeArgs Empty => new InvokeSecretInvokeArgs();
    }
}
