// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalarReturns
{
    public static class InvokeArray
    {
        public static Task<ImmutableArray<bool>> InvokeAsync(InvokeArrayArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingleAsync<ImmutableArray<bool>>("scalar-returns:index:invokeArray", args ?? new InvokeArrayArgs(), options.WithDefaults());

        public static Output<ImmutableArray<bool>> Invoke(InvokeArrayInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingle<ImmutableArray<bool>>("scalar-returns:index:invokeArray", args ?? new InvokeArrayInvokeArgs(), options.WithDefaults());

        public static Output<ImmutableArray<bool>> Invoke(InvokeArrayInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.InvokeSingle<ImmutableArray<bool>>("scalar-returns:index:invokeArray", args ?? new InvokeArrayInvokeArgs(), options.WithDefaults());
    }


    public sealed class InvokeArrayArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public InvokeArrayArgs()
        {
        }
        public static new InvokeArrayArgs Empty => new InvokeArrayArgs();
    }

    public sealed class InvokeArrayInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public InvokeArrayInvokeArgs()
        {
        }
        public static new InvokeArrayInvokeArgs Empty => new InvokeArrayInvokeArgs();
    }
}
