// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalarReturns
{
    public static class InvokeMap
    {
        public static Task<ImmutableDictionary<string, string>> InvokeAsync(InvokeMapArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingleAsync<ImmutableDictionary<string, string>>("scalar-returns:index:invokeMap", args ?? new InvokeMapArgs(), options.WithDefaults());

        public static Output<ImmutableDictionary<string, string>> Invoke(InvokeMapInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeSingle<ImmutableDictionary<string, string>>("scalar-returns:index:invokeMap", args ?? new InvokeMapInvokeArgs(), options.WithDefaults());

        public static Output<ImmutableDictionary<string, string>> Invoke(InvokeMapInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.InvokeSingle<ImmutableDictionary<string, string>>("scalar-returns:index:invokeMap", args ?? new InvokeMapInvokeArgs(), options.WithDefaults());
    }


    public sealed class InvokeMapArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public string Value { get; set; } = null!;

        public InvokeMapArgs()
        {
        }
        public static new InvokeMapArgs Empty => new InvokeMapArgs();
    }

    public sealed class InvokeMapInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public InvokeMapInvokeArgs()
        {
        }
        public static new InvokeMapInvokeArgs Empty => new InvokeMapInvokeArgs();
    }
}
