// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnion.Outputs
{

    [OutputType]
    public sealed class VariantTwo
    {
        public readonly string DiscriminantKind;
        public readonly string? Field2;

        [OutputConstructor]
        private VariantTwo(
            string discriminantKind,

            string? field2)
        {
            DiscriminantKind = discriminantKind;
            Field2 = field2;
        }
    }
}
