// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DiscriminatedUnion.Outputs
{

    [OutputType]
    public sealed class VariantOne
    {
        public readonly string DiscriminantKind;
        public readonly string? Field1;

        [OutputConstructor]
        private VariantOne(
            string discriminantKind,

            string? field1)
        {
            DiscriminantKind = discriminantKind;
            Field1 = field1;
        }
    }
}
