// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CamelNames.CoolModule
{
    [CamelNamesResourceType("camelNames:CoolModule:SomeResource")]
    public partial class SomeResource : global::Pulumi.CustomResource
    {
        [Output("resourceName")]
        public Output<string?> ResourceName { get; private set; } = null!;

        [Output("theOutput")]
        public Output<bool> TheOutput { get; private set; } = null!;


        /// <summary>
        /// Create a SomeResource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SomeResource(string name, SomeResourceArgs args, CustomResourceOptions? options = null)
            : base("camelNames:CoolModule:SomeResource", name, args ?? new SomeResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SomeResource(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("camelNames:CoolModule:SomeResource", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SomeResource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SomeResource Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new SomeResource(name, id, options);
        }
    }

    public sealed class SomeResourceArgs : global::Pulumi.ResourceArgs
    {
        [Input("resourceName")]
        public Input<string>? ResourceName { get; set; }

        [Input("theInput", required: true)]
        public Input<bool> TheInput { get; set; } = null!;

        public SomeResourceArgs()
        {
        }
        public static new SomeResourceArgs Empty => new SomeResourceArgs();
    }
}
